const hangar = [
    {
        name: "Aegis",
        image: "images/chars/aegis.png",
        affinity: "Antimatter",
        rarity: "Legendary",
        faction: "Atlas Syndicate",
        role: "Supporter",
        basic: ["shield", "hacking up 3", "atlas coordination 3"],
        charged: ["shield", "remove debuff"],
        passive: "defense up 2",
        refit: "remove debuff",
        hp: 21805,
        attack: 2474,
        defense: 2881,
        hacking: 91,
        security: 69,
        critR: 0,
        critD: 4,
        speed: 106
    },
    {
        name: "Anemone",
        image: "images/chars/anemone.png",
        affinity: "Thermal",
        rarity: "Legendary",
        faction: "Gelecek",
        role: "Defender",
        basic: ["out. damage 2", "corrosion 2"],
        charged: ["provoke"],
        passive: "damage reduction",
        refit: "repair",
        hp: 24717,
        attack: 3385,
        defense: 4581,
        hacking: 104,
        security: 58,
        critR: 0,
        critD: 0,
        speed: 69  
    },
    {
        name: "Anjian",
        image: "images/chars/anjian.png",
        affinity: "Chemical",
        rarity: "Rare",
        faction: "Tianchao",
        role: "Attacker",
        basic: ["provoke"],
        charged: ["provoke", "speed down"],
        passive: ["tianchao precision 2", "stealth"],
        refit: "",
        hp: 10747,
        attack: 5012,
        defense: 2281,
        hacking: 108,
        security: 0,
        critR: 11,
        critD: 38,
        speed: 89  
    },
    {
        name: "Arum",
        image: "images/chars/arum.png",
        affinity: "Thermal",
        rarity: "Epic",
        faction: "Gelecek",
        role: "Debuffer",
        basic: "attack down 2",
        charged: ["attack down 3", "crit rate down 3"],
        passive: "out. damage 2",
        refit: "gelecek contagion 2",
        hp: 14588,
        attack: 4351,
        defense: 2143,
        hacking: 150,
        security: 19,
        critR: 0,
        critD: 10,
        speed: 80  
    },
    {
        name: "Asphyxiator",
        image: "images/chars/asphyxiator.png",
        affinity: "Thermal",
        rarity: "Legendary",
        faction: "Marauders",
        role: "Debuffer",
        basic: ["defense down 3", "inferno 3"],
        charged: ["inc. damage 3", "stasis"],
        passive: ["overload", "marauder rage 2"],
        refit: ["crit damage increase", "hacking"],
        hp: 15977,
        attack: 4951,
        defense: 2143,
        hacking: 142,
        security: 5,
        critR: 22,
        critD: 10,
        speed: 93  
    },
    {
        name: "Berserker",
        image: "images/chars/berserker.png",
        affinity: "Electric",
        rarity: "Rare",
        faction: "Marauders",
        role: "Attacker",
        basic: "",
        charged: "",
        passive: "marauder rage 2",
        refit: "",
        hp: 11298,
        attack: 5627,
        defense: 1369,
        hacking: 92,
        security: 0,
        critR: 25,
        critD: 42,
        speed: 87  
    },
    {
        name: "Butcher",
        image: "images/chars/butcher.png",
        affinity: "Thermal",
        rarity: "Epic",
        faction: "Marauders",
        role: "Attacker",
        basic: "inferno 2",
        charged: ["block buff", "inferno 3"],
        passive: "overload",
        refit: "marauder rage 2",
        hp: 14467,
        attack: 5228,
        defense: 1920,
        hacking: 98,
        security: 0,
        critR: 23,
        critD: 42,
        speed: 90  
    },
    {
        name: "Cinya",
        image: "images/chars/cinya.png",
        affinity: "Antimatter",
        rarity: "Rare",
        faction: "Terran Combine",
        role: "Defender",
        basic: "",
        charged: "attack down 2",
        passive: "repair",
        refit: "",
        hp: 17923,
        attack: 2916,
        defense: 3833,
        hacking: 88,
        security: 65,
        critR: 0,
        critD: 20,
        speed: 60  
    },
    {
        name: "Crocus",
        image: "images/chars/crocus.png",
        affinity: "Thermal",
        rarity: "Legendary",
        faction: "Gelecek",
        role: "Debuffer",
        basic: ["corrosion 2", "stasis"],
        charged: "detonate corrosion",
        passive: "repair",
        refit: "corrosion 2",
        hp: 15977,
        attack: 4651,
        defense: 2381,
        hacking: 151,
        security: 16,
        critR: 4,
        critD: 18,
        speed: 89  
    },
    {
        name: "Crucialis",
        image: "images/chars/crucialis.png",
        affinity: "Electric",
        rarity: "Rare",
        faction: "GelecAtlas Syndicate",
        role: "Attacker",
        basic: "bypass shield",
        charged: " bypass shield",
        passive: ["shield", "atlas coordination 2"],
        refit: "",
        hp: 13366,
        attack: 4397,
        defense: 1537,
        hacking: 90,
        security: 17,
        critR: 17,
        critD: 46,
        speed: 85  
    },
    {
      name: "Cultivator",
      image: "images/chars/cultivator.png",
      affinity: "Chemical",
      rarity: "Legendary",
      faction: "Binderburg",
      role: "Supporter",
      basic: ["defense up 3","remove debuff"],
      charged: ["inc. damage down 3", "binderburg resilience 3", "remove debuff"],
      passive: "repair",
      refit: "repair",
      hp: 22413,
      attack: 1770,
      defense: 3265,
      hacking: 99,
      security: 73,
      critR: 4,
      critD: 20,
      speed: 95  
  },
  {
    name: "Curator",
    image: "images/chars/curator.png",
    affinity: "Chemical",
    rarity: "Legendary",
    faction: "Binderburg",
    role: "Debuffer",
    basic: "attack down 3",
    charged: "out. damage down 3",
    passive: "",
    refit: "security down 3",
    hp: 19033,
    attack: 4562,
    defense: 2262,
    hacking: 152,
    security: 24,
    critR: 2,
    critD: 30,
    speed: 77  
  },  
  {
    name: "Defiant",
    image: "images/chars/defiant.png",
    affinity: "Chemical",
    rarity: "Epic",
    faction: "Frontier Legion",
    role: "Defender",
    basic: "provoke",
    charged: "stasis",
    passive: "shield",
    refit: "",
    hp: 21534,
    attack: 3362,
    defense: 4261,
    hacking: 85,
    security: 54,
    critR: 7,
    critD: 12,
    speed: 71  
  },
  {
    name: "Demolisher",
    image: "images/chars/demolisher.png",
    affinity: "Antimatter",
    rarity: "Legendary",
    faction: "Marauders",
    role: "Attacker",
    basic: "bomb 3",
    charged: "detonate bomb",
    passive: "",
    refit: ["bypass shield", "bypass defense"],
    hp: 13366,
    attack: 5535,
    defense: 2593,
    hacking: 103,
    security: 1,
    critR: 28,
    critD: 34,
    speed: 95  
  },
  {
    name: "Faust",
    image: "images/chars/faust.png",
    affinity: "Thermal",
    rarity: "Rare",
    faction: "Everliving",
    role: "Supporter",
    basic: "security up 2",
    charged: ["repair", "everliving regeneration 2", "defense up 2"],
    passive: "remove buff",
    refit: "",
    hp: 11907,
    attack: 1536,
    defense: 3001,
    hacking: 91,
    security: 62,
    critR: 5,
    critD: 20,
    speed: 95  
  },
  {
    name: "Flamel",
    image: "images/chars/flamel.png",
    affinity: "Antimatter",
    rarity: "Epic",
    faction: "Everliving",
    role: "Supporter",
    basic: ["repair", "repair over time"],
    charged: ["repair", "repair over time 2"],
    passive: "speed down",
    refit: "stasis",
    hp: 17650,
    attack: 1666,
    defense: 3121,
    hacking: 93,
    security: 56,
    critR: 7,
    critD: 20,
    speed: 97  
  },
  {
    name: "Fronline",
    image: "images/chars/frontline.png",
    affinity: "Electric",
    rarity: "Legendary",
    faction: "Atlas Syndicate",
    role: "Attacker",
    basic: ["shield", "bypass shield"],
    charged: "lose charge",
    passive: "attack up 3",
    refit: "fill charge",
    hp: 10471,
    attack: 5413,
    defense: 2328,
    hacking: 109,
    security: 12,
    critR: 16,
    critD: 62,
    speed: 84  
  },
  {
    name: "Gallant",
    image: "images/chars/gallant.png",
    affinity: "Thermal",
    rarity: "Rare",
    faction: "Frontier Legion",
    role: "Attacker",
    basic: "",
    charged: "stasis",
    passive: "legion discipline 2",
    refit: "",
    hp: 13366,
    attack: 5105,
    defense: 2473,
    hacking: 95,
    security: 14,
    critR: 8,
    critD: 46,
    speed: 86  
  },
  {
    name: "Grif",
    image: "images/chars/grif.png",
    affinity: "Chemical",
    rarity: "Legendary",
    faction: "Xaoc",
    role: "Supporter",
    basic: ["out. damage up 3", "hacking up 3"],
    charged: ["crit damage up 3", "attack up 3"],
    passive: "",
    refit: "disable",
    hp: 16809,
    attack: 3463,
    defense: 2808,
    hacking: 92,
    security: 62,
    critR: 18,
    critD: 34,
    speed: 97  
  },
  {
    name: "Harvester",
    image: "images/chars/harvester.png",
    affinity: "Electric",
    rarity: "Rare",
    faction: "Binderbug",
    role: "Supporter",
    basic: ["crit rate up 2", "attack up 2", "remove debuff"],
    charged: ["crit damage up 3", "attack up 3"],
    passive: "",
    refit: "speed up",
    hp: 16809,
    attack: 3463,
    defense: 2808,
    hacking: 92,
    security: 62,
    critR: 18,
    critD: 34,
    speed: 97  
  },
  {
    name: "Hayyan",
    image: "images/chars/hayyan.png",
    affinity: "Electric",
    rarity: "Legendary",
    faction: "Everliving",
    role: "Supporter",
    basic: ["repair", "hacking up 2", "remove debuff"],
    charged: ["repair", "cheat death","fill charge"],
    passive: "repair",
    refit: "repair",
    hp: 19052,
    attack: 2396,
    defense: 2928,
    hacking: 94,
    security: 65,
    critR: 8,
    critD: 20,
    speed: 98  
  },
  {
    name: "Heliodor",
    image: "images/chars/heliodor.png",
    affinity: "Thermal",
    rarity: "Epic",
    faction: "MPL",
    role: "Supporter",
    basic: ["inc. damage down 2", "defense up 3"],
    charged: ["security up 3", "matrix defense"],
    passive: ["repair", "remove debuff"],
    refit: "",
    hp: 16389,
    attack: 1536,
    defense: 2496,
    hacking: 90,
    security: 69,
    critR: 7,
    critD: 20,
    speed: 92  
  },
  {
    name: "Hermes",
    image: "images/chars/hermes.png",
    affinity: "Thermal",
    rarity: "Legendary",
    faction: "Everliving",
    role: "Supporter",
    basic: "repair",
    charged: ["cheat death", "fill charge", "repair"],
    passive: "fill charge",
    refit: "everliving regeneration",
    hp: 22699,
    attack: 1927,
    defense: 3361,
    hacking: 94,
    security: 61,
    critR: 8,
    critD: 36,
    speed: 85  
  },
  {
    name: "Huanying",
    image: "images/chars/huanying.png",
    affinity: "Thermal",
    rarity: "Rare",
    faction: "Tianchao",
    role: "Debuffer",
    basic: "bomb",
    charged: ["concentrate fire", "bomb 2"],
    passive: "stealth",
    refit: "tianchao precision 2",
    hp: 13338,
    attack: 4441,
    defense: 1405,
    hacking: 143,
    security: 11,
    critR: 5,
    critD: 22,
    speed: 83  
  },
  {
    name: "Ionscorp",
    image: "images/chars/ionscorp.png",
    affinity: "Chemical",
    rarity: "Rare",
    faction: "Atlas Syndicate",
    role: "Attacker",
    basic: "",
    charged: "disable",
    passive: ["shield", "atlas coordination 2"],
    refit: "tianchao precision 2",
    hp: 13366,
    attack: 4951,
    defense: 1537,
    hacking: 102,
    security: 17,
    critR: 5,
    critD: 54,
    speed: 81  
  },
  {
    name: "Iridium",
    image: "images/chars/iridium.png",
    affinity: "Antimatter",
    rarity: "Legendary",
    faction: "MPL",
    role: "Defender",
    basic: ["repair", "bypass shield"],
    charged: ["disable", "bypass shield"],
    passive: "",
    refit: "speed down 2",
    hp: 28825,
    attack: 2396,
    defense: 3857,
    hacking: 123,
    security: 41,
    critR: 1,
    critD: 4,
    speed: 63  
  },
  {
    name: "Judge",
    image: "images/chars/judge.png",
    affinity: "Electric",
    rarity: "Legendary",
    faction: "Frontier Legion",
    role: "Attacker",
    basic: ["concentrate fire", "bypass defense"],
    charged: "bypass defense",
    passive: "",
    refit: "",
    hp: 12952,
    attack: 6119,
    defense: 1969,
    hacking: 98,
    security: 9,
    critR: 19,
    critD: 54,
    speed: 94  
  },
  {
    name: "Kafa",
    image: "images/chars/kafa.png",
    affinity: "Chemical",
    rarity: "Rare",
    faction: "Terran Combine",
    role: "Defender",
    basic: "defense down",
    charged: ["defense down 2", "provoke"],
    passive: "terran tenacity",
    refit: "terran tenacity 2",
    hp: 17923,
    attack: 1846,
    defense: 4261,
    hacking: 88,
    security: 61,
    critR: 0,
    critD: 20,
    speed: 60  
  },
  {
    name: "Kinetik",
    image: "images/chars/kinetik.png",
    affinity: "Electric",
    rarity: "Rare",
    faction: "Atlas Syndicate",
    role: "Defender",
    basic: "defense down",
    charged: ["defense down 2", "out. damage 2"],
    passive: "shield",
    refit: "",
    hp: 23341,
    attack: 2530,
    defense: 3643,
    hacking: 90,
    security: 59,
    critR: 2,
    critD: 4,
    speed: 64  
  },
  {
    name: "Laika",
    image: "images/chars/laika.png",
    affinity: "Thermal",
    rarity: "Rare",
    faction: "Xaoc",
    role: "Defender",
    basic: "remove debuff",
    charged: "bypass defense",
    passive: "shield",
    refit: "",
    hp: 21256,
    attack: 3125,
    defense: 3571,
    hacking: 79,
    security: 41,
    critR: 12,
    critD: 34,
    speed: 72  
  },
  {
    name: "Larkspur",
    image: "images/chars/larkspur.png",
    affinity: "Electric",
    rarity: "Rare",
    faction: "Gelecek",
    role: "Debuffer",
    basic: "inc. repair down 2",
    charged: ["inc. damage up 2", "inc. repair down 3"],
    passive: "gelecek contagion 2",
    refit: "",
    hp: 13893,
    attack: 4201,
    defense: 2881,
    hacking: 71489,
    security: 17,
    critR: 0,
    critD: 2,
    speed: 78  
  },
  {
    name: "Liberator",
    image: "images/chars/liberator.png",
    affinity: "Thermal",
    rarity: "Legendary",
    faction: "Frontier Legion",
    role: "Attacker",
    basic: "bypass shield",
    charged: ["bypass shield", "legion discipline 3"],
    passive: "fill charge",
    refit: "extra action",
    hp: 15432,
    attack: 5566,
    defense: 2401,
    hacking: 86,
    security: 9,
    critR: 23,
    critD: 54,
    speed: 94  
  },
  {
    name: "Los",
    image: "images/chars/los.png",
    affinity: "Electric",
    rarity: "Legendary",
    faction: "Xaoc ",
    role: "Attacker",
    basic: "",
    charged: "xaoc swiftness 3",
    passive: ["block damage", "out. damage"],
    refit: "fill charge",
    hp: 10885,
    attack: 6028,
    defense: 2689,
    hacking: 102,
    security: 9,
    critR: 18,
    critD: 60,
    speed: 84  
  },
  {
    name: "Luxx",
    image: "images/chars/luxx.png",
    affinity: "Antimatter",
    rarity: "Epic",
    faction: "Atlas Syndicate ",
    role: "Attacker",
    basic: "bypass shield",
    charged: ["bypass shield", "atlas coordination 2"],
    passive: "blast",
    refit: "shield",
    hp: 11574,
    attack: 5105,
    defense: 2088,
    hacking: 92,
    security: 19,
    critR: 15,
    critD: 62,
    speed: 83  
  },
  {
    name: "Madax",
    image: "images/chars/madax.png",
    affinity: "Electric",
    rarity: "Legendary",
    faction: "Terran Combine",
    role: "Defender",
    basic: "taunt",
    charged: "terran bolster",
    passive: "repair",
    refit: "",
    hp: 22486,
    attack: 2474,
    defense: 4619,
    hacking: 91,
    security: 68,
    critR: 5,
    critD: 12,
    speed: 68  
  },
  {
    name: "Magnolia",
    image: "images/chars/magnolia.png",
    affinity: "Electric",
    rarity: "Legendary",
    faction: "Terran Combine",
    role: "Defender",
    basic: "taunt",
    charged: "terran bolster",
    passive: "repair",
    refit: "",
    hp: 22486,
    attack: 2474,
    defense: 4619,
    hacking: 91,
    security: 68,
    critR: 5,
    critD: 12,
    speed: 68  
  },
  {
    name: "Mangler",
    image: "images/chars/mangler.png",
    affinity: "Electric",
    rarity: "Legendary",
    faction: "Terran Combine",
    role: "Defender",
    basic: "taunt",
    charged: "terran bolster",
    passive: "repair",
    refit: "",
    hp: 22486,
    attack: 2474,
    defense: 4619,
    hacking: 91,
    security: 68,
    critR: 5,
    critD: 12,
    speed: 68  
  },
  {
    name: "Medved",
    image: "images/chars/medved.png",
    affinity: "Electric",
    rarity: "Legendary",
    faction: "Terran Combine",
    role: "Defender",
    basic: "taunt",
    charged: "terran bolster",
    passive: "repair",
    refit: "",
    hp: 22486,
    attack: 2474,
    defense: 4619,
    hacking: 91,
    security: 68,
    critR: 5,
    critD: 12,
    speed: 68  
  },
  {
    name: "Meiying",
    image: "images/chars/meiying.png",
    affinity: "Electric",
    rarity: "Legendary",
    faction: "Terran Combine",
    role: "Defender",
    basic: "taunt",
    charged: "terran bolster",
    passive: "repair",
    refit: "",
    hp: 22486,
    attack: 2474,
    defense: 4619,
    hacking: 91,
    security: 68,
    critR: 5,
    critD: 12,
    speed: 68  
  },
  {
    name: "Morao",
    image: "images/chars/morao.png",
    affinity: "Electric",
    rarity: "Legendary",
    faction: "Terran Combine",
    role: "Defender",
    basic: "taunt",
    charged: "terran bolster",
    passive: "repair",
    refit: "",
    hp: 22486,
    attack: 2474,
    defense: 4619,
    hacking: 91,
    security: 68,
    critR: 5,
    critD: 12,
    speed: 68  
  },
  {
    name: "Nemesis",
    image: "images/chars/nemesis.png",
    affinity: "Electric",
    rarity: "Legendary",
    faction: "Terran Combine",
    role: "Defender",
    basic: "taunt",
    charged: "terran bolster",
    passive: "repair",
    refit: "",
    hp: 22486,
    attack: 2474,
    defense: 4619,
    hacking: 91,
    security: 68,
    critR: 5,
    critD: 12,
    speed: 68  
  },
  {
    name: "Nosorog",
    image: "images/chars/nosorog.png",
    affinity: "Electric",
    rarity: "Legendary",
    faction: "Terran Combine",
    role: "Defender",
    basic: "taunt",
    charged: "terran bolster",
    passive: "repair",
    refit: "",
    hp: 22486,
    attack: 2474,
    defense: 4619,
    hacking: 91,
    security: 68,
    critR: 5,
    critD: 12,
    speed: 68  
  },
  {
    name: "Nuqtu",
    image: "images/chars/nuqtu.png",
    affinity: "Electric",
    rarity: "Legendary",
    faction: "Terran Combine",
    role: "Defender",
    basic: "taunt",
    charged: "terran bolster",
    passive: "repair",
    refit: "",
    hp: 22486,
    attack: 2474,
    defense: 4619,
    hacking: 91,
    security: 68,
    critR: 5,
    critD: 12,
    speed: 68  
  },
  {
    name: "Obsidian",
    image: "images/chars/obsidian.png",
    affinity: "Electric",
    rarity: "Legendary",
    faction: "Terran Combine",
    role: "Defender",
    basic: "taunt",
    charged: "terran bolster",
    passive: "repair",
    refit: "",
    hp: 22486,
    attack: 2474,
    defense: 4619,
    hacking: 91,
    security: 68,
    critR: 5,
    critD: 12,
    speed: 68  
  },
  {
    name: "Opal",
    image: "images/chars/opal.png",
    affinity: "Electric",
    rarity: "Legendary",
    faction: "Terran Combine",
    role: "Defender",
    basic: "taunt",
    charged: "terran bolster",
    passive: "repair",
    refit: "",
    hp: 22486,
    attack: 2474,
    defense: 4619,
    hacking: 91,
    security: 68,
    critR: 5,
    critD: 12,
    speed: 68  
  },
  {
    name: "Panguan",
    image: "images/chars/panguan.png",
    affinity: "Electric",
    rarity: "Legendary",
    faction: "Terran Combine",
    role: "Defender",
    basic: "taunt",
    charged: "terran bolster",
    passive: "repair",
    refit: "",
    hp: 22486,
    attack: 2474,
    defense: 4619,
    hacking: 91,
    security: 68,
    critR: 5,
    critD: 12,
    speed: 68  
  },
  {
    name: "Panon",
    image: "images/chars/panon.png",
    affinity: "Electric",
    rarity: "Legendary",
    faction: "Terran Combine",
    role: "Defender",
    basic: "taunt",
    charged: "terran bolster",
    passive: "repair",
    refit: "",
    hp: 22486,
    attack: 2474,
    defense: 4619,
    hacking: 91,
    security: 68,
    critR: 5,
    critD: 12,
    speed: 68  
  },
  {
    name: "Paracelsus",
    image: "images/chars/paracelsus.png",
    affinity: "Electric",
    rarity: "Legendary",
    faction: "Terran Combine",
    role: "Defender",
    basic: "taunt",
    charged: "terran bolster",
    passive: "repair",
    refit: "",
    hp: 22486,
    attack: 2474,
    defense: 4619,
    hacking: 91,
    security: 68,
    critR: 5,
    critD: 12,
    speed: 68  
  },
  {
    name: "Prospect",
    image: "images/chars/prospect.png",
    affinity: "Electric",
    rarity: "Legendary",
    faction: "Terran Combine",
    role: "Defender",
    basic: "taunt",
    charged: "terran bolster",
    passive: "repair",
    refit: "",
    hp: 22486,
    attack: 2474,
    defense: 4619,
    hacking: 91,
    security: 68,
    critR: 5,
    critD: 12,
    speed: 68  
  },
  {
    name: "Purifier",
    image: "images/chars/purifier.png",
    affinity: "Electric",
    rarity: "Legendary",
    faction: "Terran Combine",
    role: "Defender",
    basic: "taunt",
    charged: "terran bolster",
    passive: "repair",
    refit: "",
    hp: 22486,
    attack: 2474,
    defense: 4619,
    hacking: 91,
    security: 68,
    critR: 5,
    critD: 12,
    speed: 68  
  },
  {
    name: "Ravager",
    image: "images/chars/ravager.png",
    affinity: "Electric",
    rarity: "Legendary",
    faction: "Terran Combine",
    role: "Defender",
    basic: "taunt",
    charged: "terran bolster",
    passive: "repair",
    refit: "",
    hp: 22486,
    attack: 2474,
    defense: 4619,
    hacking: 91,
    security: 68,
    critR: 5,
    critD: 12,
    speed: 68  
  },
  {
    name: "Redeemer",
    image: "images/chars/redeemer.png",
    affinity: "Electric",
    rarity: "Legendary",
    faction: "Terran Combine",
    role: "Defender",
    basic: "taunt",
    charged: "terran bolster",
    passive: "repair",
    refit: "",
    hp: 22486,
    attack: 2474,
    defense: 4619,
    hacking: 91,
    security: 68,
    critR: 5,
    critD: 12,
    speed: 68  
  },
  {
    name: "Refine",
    image: "images/chars/refine.png",
    affinity: "Electric",
    rarity: "Legendary",
    faction: "Terran Combine",
    role: "Defender",
    basic: "taunt",
    charged: "terran bolster",
    passive: "repair",
    refit: "",
    hp: 22486,
    attack: 2474,
    defense: 4619,
    hacking: 91,
    security: 68,
    critR: 5,
    critD: 12,
    speed: 68  
  },
  {
    name: "Rikra",
    image: "images/chars/rikra.png",
    affinity: "Electric",
    rarity: "Legendary",
    faction: "Terran Combine",
    role: "Defender",
    basic: "taunt",
    charged: "terran bolster",
    passive: "repair",
    refit: "",
    hp: 22486,
    attack: 2474,
    defense: 4619,
    hacking: 91,
    security: 68,
    critR: 5,
    critD: 12,
    speed: 68  
  },
  {
    name: "Ripper",
    image: "images/chars/ripper.png",
    affinity: "Electric",
    rarity: "Legendary",
    faction: "Terran Combine",
    role: "Defender",
    basic: "taunt",
    charged: "terran bolster",
    passive: "repair",
    refit: "",
    hp: 22486,
    attack: 2474,
    defense: 4619,
    hacking: 91,
    security: 68,
    critR: 5,
    critD: 12,
    speed: 68  
  },
  {
    name: "Rys",
    image: "images/chars/rys.png",
    affinity: "Electric",
    rarity: "Legendary",
    faction: "Terran Combine",
    role: "Defender",
    basic: "taunt",
    charged: "terran bolster",
    passive: "repair",
    refit: "",
    hp: 22486,
    attack: 2474,
    defense: 4619,
    hacking: 91,
    security: 68,
    critR: 5,
    critD: 12,
    speed: 68  
  },
  {
    name: "Salvation",
    image: "images/chars/salvation.png",
    affinity: "Electric",
    rarity: "Legendary",
    faction: "Terran Combine",
    role: "Defender",
    basic: "taunt",
    charged: "terran bolster",
    passive: "repair",
    refit: "",
    hp: 22486,
    attack: 2474,
    defense: 4619,
    hacking: 91,
    security: 68,
    critR: 5,
    critD: 12,
    speed: 68  
  },
  {
    name: "Sansi",
    image: "images/chars/sansi.png",
    affinity: "Electric",
    rarity: "Legendary",
    faction: "Terran Combine",
    role: "Defender",
    basic: "taunt",
    charged: "terran bolster",
    passive: "repair",
    refit: "",
    hp: 22486,
    attack: 2474,
    defense: 4619,
    hacking: 91,
    security: 68,
    critR: 5,
    critD: 12,
    speed: 68  
  },
  {
    name: "Sebufa",
    image: "images/chars/sebufa.png",
    affinity: "Electric",
    rarity: "Legendary",
    faction: "Terran Combine",
    role: "Defender",
    basic: "taunt",
    charged: "terran bolster",
    passive: "repair",
    refit: "",
    hp: 22486,
    attack: 2474,
    defense: 4619,
    hacking: 91,
    security: 68,
    critR: 5,
    critD: 12,
    speed: 68  
  },
  {
    name: "Sentinel",
    image: "images/chars/sentinel.png",
    affinity: "Electric",
    rarity: "Legendary",
    faction: "Terran Combine",
    role: "Defender",
    basic: "taunt",
    charged: "terran bolster",
    passive: "repair",
    refit: "",
    hp: 22486,
    attack: 2474,
    defense: 4619,
    hacking: 91,
    security: 68,
    critR: 5,
    critD: 12,
    speed: 68  
  },
  {
    name: "Sha Xing",
    image: "images/chars/sha_xing.png",
    affinity: "Electric",
    rarity: "Legendary",
    faction: "Terran Combine",
    role: "Defender",
    basic: "taunt",
    charged: "terran bolster",
    passive: "repair",
    refit: "",
    hp: 22486,
    attack: 2474,
    defense: 4619,
    hacking: 91,
    security: 68,
    critR: 5,
    critD: 12,
    speed: 68  
  },
  {
    name: "Shashou",
    image: "images/chars/shashou.png",
    affinity: "Electric",
    rarity: "Legendary",
    faction: "Terran Combine",
    role: "Defender",
    basic: "taunt",
    charged: "terran bolster",
    passive: "repair",
    refit: "",
    hp: 22486,
    attack: 2474,
    defense: 4619,
    hacking: 91,
    security: 68,
    critR: 5,
    critD: 12,
    speed: 68  
  },
  {
    name: "Shelter",
    image: "images/chars/shelter.png",
    affinity: "Electric",
    rarity: "Legendary",
    faction: "Terran Combine",
    role: "Defender",
    basic: "taunt",
    charged: "terran bolster",
    passive: "repair",
    refit: "",
    hp: 22486,
    attack: 2474,
    defense: 4619,
    hacking: 91,
    security: 68,
    critR: 5,
    critD: 12,
    speed: 68  
  },
  {
    name: "Sheperd",
    image: "images/chars/sheperd.png",
    affinity: "Electric",
    rarity: "Legendary",
    faction: "Terran Combine",
    role: "Defender",
    basic: "taunt",
    charged: "terran bolster",
    passive: "repair",
    refit: "",
    hp: 22486,
    attack: 2474,
    defense: 4619,
    hacking: 91,
    security: 68,
    critR: 5,
    critD: 12,
    speed: 68  
  },
  {
    name: "SnapDragon",
    image: "images/chars/snapdragon.png",
    affinity: "Electric",
    rarity: "Legendary",
    faction: "Terran Combine",
    role: "Defender",
    basic: "taunt",
    charged: "terran bolster",
    passive: "repair",
    refit: "",
    hp: 22486,
    attack: 2474,
    defense: 4619,
    hacking: 91,
    security: 68,
    critR: 5,
    critD: 12,
    speed: 68  
  },
  {
    name: "Sokol",
    image: "images/chars/sokol.png",
    affinity: "Electric",
    rarity: "Legendary",
    faction: "Terran Combine",
    role: "Defender",
    basic: "taunt",
    charged: "terran bolster",
    passive: "repair",
    refit: "",
    hp: 22486,
    attack: 2474,
    defense: 4619,
    hacking: 91,
    security: 68,
    critR: 5,
    critD: 12,
    speed: 68  
  },
  {
    name: "Stalwart",
    image: "images/chars/stalwart.png",
    affinity: "Electric",
    rarity: "Legendary",
    faction: "Terran Combine",
    role: "Defender",
    basic: "taunt",
    charged: "terran bolster",
    passive: "repair",
    refit: "",
    hp: 22486,
    attack: 2474,
    defense: 4619,
    hacking: 91,
    security: 68,
    critR: 5,
    critD: 12,
    speed: 68  
  },
  {
    name: "Sustainer",
    image: "images/chars/sustainer.png",
    affinity: "Electric",
    rarity: "Legendary",
    faction: "Terran Combine",
    role: "Defender",
    basic: "taunt",
    charged: "terran bolster",
    passive: "repair",
    refit: "",
    hp: 22486,
    attack: 2474,
    defense: 4619,
    hacking: 91,
    security: 68,
    critR: 5,
    critD: 12,
    speed: 68  
  },
  {
    name: "Torcher",
    image: "images/chars/torcher.png",
    affinity: "Electric",
    rarity: "Legendary",
    faction: "Terran Combine",
    role: "Defender",
    basic: "taunt",
    charged: "terran bolster",
    passive: "repair",
    refit: "",
    hp: 22486,
    attack: 2474,
    defense: 4619,
    hacking: 91,
    security: 68,
    critR: 5,
    critD: 12,
    speed: 68  
  },
  {
    name: "Tycho",
    image: "images/chars/tycho.png",
    affinity: "Electric",
    rarity: "Legendary",
    faction: "Terran Combine",
    role: "Defender",
    basic: "taunt",
    charged: "terran bolster",
    passive: "repair",
    refit: "",
    hp: 22486,
    attack: 2474,
    defense: 4619,
    hacking: 91,
    security: 68,
    critR: 5,
    critD: 12,
    speed: 68  
  },
  {
    name: "Valerian",
    image: "images/chars/valerian.png",
    affinity: "Electric",
    rarity: "Legendary",
    faction: "Terran Combine",
    role: "Defender",
    basic: "taunt",
    charged: "terran bolster",
    passive: "repair",
    refit: "",
    hp: 22486,
    attack: 2474,
    defense: 4619,
    hacking: 91,
    security: 68,
    critR: 5,
    critD: 12,
    speed: 68  
  },
  {
    name: "Valiant",
    image: "images/chars/valiant.png",
    affinity: "Electric",
    rarity: "Legendary",
    faction: "Terran Combine",
    role: "Defender",
    basic: "taunt",
    charged: "terran bolster",
    passive: "repair",
    refit: "",
    hp: 22486,
    attack: 2474,
    defense: 4619,
    hacking: 91,
    security: 68,
    critR: 5,
    critD: 12,
    speed: 68  
  },
  {
    name: "Voron",
    image: "images/chars/voron.png",
    affinity: "Electric",
    rarity: "Legendary",
    faction: "Terran Combine",
    role: "Defender",
    basic: "taunt",
    charged: "terran bolster",
    passive: "repair",
    refit: "",
    hp: 22486,
    attack: 2474,
    defense: 4619,
    hacking: 91,
    security: 68,
    critR: 5,
    critD: 12,
    speed: 68  
  },
  {
    name: "Warden",
    image: "images/chars/warden.png",
    affinity: "Electric",
    rarity: "Legendary",
    faction: "Terran Combine",
    role: "Defender",
    basic: "taunt",
    charged: "terran bolster",
    passive: "repair",
    refit: "",
    hp: 22486,
    attack: 2474,
    defense: 4619,
    hacking: 91,
    security: 68,
    critR: 5,
    critD: 12,
    speed: 68  
  },
  {
    name: "Xcellence",
    image: "images/chars/xcellence.png",
    affinity: "Electric",
    rarity: "Legendary",
    faction: "Terran Combine",
    role: "Defender",
    basic: "taunt",
    charged: "terran bolster",
    passive: "repair",
    refit: "",
    hp: 22486,
    attack: 2474,
    defense: 4619,
    hacking: 91,
    security: 68,
    critR: 5,
    critD: 12,
    speed: 68  
  },
  {
    name: "Yarrow",
    image: "images/chars/yarrow.png",
    affinity: "Electric",
    rarity: "Legendary",
    faction: "Terran Combine",
    role: "Defender",
    basic: "taunt",
    charged: "terran bolster",
    passive: "repair",
    refit: "",
    hp: 22486,
    attack: 2474,
    defense: 4619,
    hacking: 91,
    security: 68,
    critR: 5,
    critD: 12,
    speed: 68  
  },
  {
    name: "Yazid",
    image: "images/chars/yazid.png",
    affinity: "Electric",
    rarity: "Legendary",
    faction: "Terran Combine",
    role: "Defender",
    basic: "taunt",
    charged: "terran bolster",
    passive: "repair",
    refit: "",
    hp: 22486,
    attack: 2474,
    defense: 4619,
    hacking: 91,
    security: 68,
    critR: 5,
    critD: 12,
    speed: 68  
  },
  {
    name: "Yuyan",
    image: "images/chars/yuyan.png",
    affinity: "Electric",
    rarity: "Legendary",
    faction: "Terran Combine",
    role: "Defender",
    basic: "taunt",
    charged: "terran bolster",
    passive: "repair",
    refit: "",
    hp: 22486,
    attack: 2474,
    defense: 4619,
    hacking: 91,
    security: 68,
    critR: 5,
    critD: 12,
    speed: 68  
  },
  
]


//Gallery
  const galleryContainer = document.querySelector(".gallery");
  
  hangar.forEach((ship) => {
    const card = document.createElement("div");
    card.classList.add("card");
  
    if (ship.rarity.toLowerCase() === "legendary") {
      card.classList.add("legendary-card");
    } else if (ship.rarity.toLowerCase() === "epic") {
      card.classList.add("epic-card");
    } else if (ship.rarity.toLowerCase() === "rare") {
      card.classList.add("rare-card");
    }
  
    card.setAttribute("data-name", ship.name);
  
    const affinityIcon = document.createElement("div");
    affinityIcon.classList.add("affinity-icon");
  
    if (ship.affinity.toLowerCase() === "antimatter") {
      affinityIcon.classList.add("antimatter-affinity");
    } else if (ship.affinity.toLowerCase() === "chemical") {
      affinityIcon.classList.add("chemical-affinity");
    } else if (ship.affinity.toLowerCase() === "thermal") {
      affinityIcon.classList.add("thermal-affinity");
    } else if (ship.affinity.toLowerCase() === "electric") {
      affinityIcon.classList.add("electric-affinity");
    }
  
    const roleIcon = document.createElement("i");
    roleIcon.classList.add("role-icon");
  
    if (ship.role === "Supporter") {
      roleIcon.classList.add("bi", "bi-plus-circle");
    } else if (ship.role === "Defender") {
      roleIcon.classList.add("bi", "bi-shield-shaded");
    } else if (ship.role === "Attacker") {
      roleIcon.classList.add("bi", "bi-lightning-charge-fill");
    } else if (ship.role === "Debuffer") {
      roleIcon.classList.add("bi", "bi-bug-fill");
    } else {
      roleIcon.classList.add("bi", "bi-question-circle-fill");
    }
  
    card.appendChild(affinityIcon);
    card.appendChild(roleIcon);
  
    const image = document.createElement("img");
    image.src = ship.image;
    image.alt = ship.name;
    
    card.appendChild(image);
    
    galleryContainer.appendChild(card);
  });
  


