var hangar = [
    {
        name: "Aegis",
        image: "images/chars/aegis.png",
        target: "images/pattern/pattern-aegis.png",
        affinity: "Antimatter",
        rarity: "Legendary",
        faction: "Atlas Syndicate",
        role: "Supporter",
        basic: ["shield", "hacking up 3", "atlas coordination 3"],
        charged: ["shield", "remove debuff"],
        passive: "defense up 2",
        refit: "remove debuff",
        basicA: "Apply shield, apply HACKING UP III and ATLAS COORDINATION III.",
chargedA: "Apply shield and remove 2 debuffs.",
cooldown: "4",
passiveM: "When ally within active pattern has their shield destroyed : apply DEFENSE UP II and remove all debuffs.",
        hp: 21805,
        attack: 2474,
        defense: 2881,
        hacking: 91,
        security: 69,
        critR: 0,
        critD: 4,
        speed: 106
    },
    {
        name: "Anemone",
        image: "images/chars/anemone.png",
        affinity: "Thermal",
        rarity: "Legendary",
        faction: "Gelecek",
        role: "Defender",
        basic: ["out. damage down 2", "corrosion 2"],
        charged: ["provoke"],
        passive: "damage reduction",
        refit: "repair self",
        basicA: "Deal damage, apply OUT. DAMAGE DOWN II and CORROSION II.",
chargedA: "Deal damage. If enemy has a debuff: apply PROVOKE.",
cooldown: "4",
passiveM: "This ship takes 20% less damage from debuffed enemies. When an enemy takes damage from corrosion: Repair Self.",
        hp: 24717,
        attack: 3385,
        defense: 4581,
        hacking: 104,
        security: 58,
        critR: 0,
        critD: 0,
        speed: 69  
    },
    {
        name: "Anjian",
        image: "images/chars/anjian.png",
        affinity: "Chemical",
        rarity: "Rare",
        faction: "Tianchao",
        role: "Attacker",
        basic: ["provoke"],
        charged: ["provoke", "speed down"],
        passive: ["tianchao precision 2", "stealth"],
        refit: "",
        basicA: "Deal damage (ignore taunt and provoke).",
chargedA: "Deal damage (ignore taunt and provoke) and apply SPEED DOWN II.",
cooldown: "3",
passiveM: "When damaging a debuffer/supporter: Gain STEALTH and gain TIANCHAO PRECISION II.",
        hp: 10747,
        attack: 5012,
        defense: 2281,
        hacking: 108,
        security: 0,
        critR: 11,
        critD: 38,
        speed: 89  
    },
    {
        name: "Arum",
        image: "images/chars/arum.png",
        affinity: "Thermal",
        rarity: "Epic",
        faction: "Gelecek",
        role: "Debuffer",
        basic: "attack down 2",
        charged: ["attack down 3", "crit rate down 3"],
        passive: "out. damage 2",
        refit: "gelecek contagion 2",
        basicA: "Deal damage and apply ATTACK DOWN II.",
chargedA: "Deal damage, apply ATTACK DOWN III and CRIT RATE DOWN III.",
cooldown: "3",
passiveM: "When an enemy cleanses a debuff: Apply OUT, DAMAGE DOWN I and apply GELECEK CONTAGION II to all allies.",
        hp: 14588,
        attack: 4351,
        defense: 2143,
        hacking: 150,
        security: 19,
        critR: 0,
        critD: 10,
        speed: 80  
    },
    {
        name: "Asphyxiator",
        image: "images/chars/asphyxiator.png",
        affinity: "Thermal",
        rarity: "Legendary",
        faction: "Marauders",
        role: "Debuffer",
        basic: ["defense down 3", "inferno 3"],
        charged: ["inc. damage up 3", "stasis"],
        passive: ["overload", "marauder rage 2"],
        refit: ["crit damage increase", "hacking"],
        basicA: "Deal damage and apply DEFENSE DOWN III and INFERNO III to units adjacent to enemy.",
chargedA: "Deal damage and apply INC. DAMAGE UP III. If adjacent enemies have>2 debuffs: Apply STASIS to units adjacent to enemy.",
cooldown: "4",
passiveM: "Start of round, if there are any enemies with >2 debuffs on them: Gain OVERLOAD and gain MARAUDER RAGE II. On kill: Lose OVERLOAD. When affected by MARAUDER RAGE II: Crit damage increased by 30% and hacking by 40%.",
        hp: 15977,
        attack: 4951,
        defense: 2143,
        hacking: 142,
        security: 5,
        critR: 22,
        critD: 10,
        speed: 93  
    },
    {
        name: "Berserker",
        image: "images/chars/berserker.png",
        affinity: "Electric",
        rarity: "Rare",
        faction: "Marauders",
        role: "Attacker",
        basic: "",
        charged: "",
        passive: "marauder rage 2",
        refit: "",
        basicA: "Deal damage.",
chargedA: "Deal damage.",
cooldown: "3",
passiveM: "When hitting >2 enemies: Gain MARAUDER RAGE II.",
        hp: 11298,
        attack: 5627,
        defense: 1369,
        hacking: 92,
        security: 0,
        critR: 25,
        critD: 42,
        speed: 87  
    },
    {
        name: "Butcher",
        image: "images/chars/butcher.png",
        affinity: "Thermal",
        rarity: "Epic",
        faction: "Marauders",
        role: "Attacker",
        basic: "inferno 2",
        charged: ["block buff", "inferno 3"],
        passive: "overload",
        refit: "marauder rage 2",
        basicA: "Deal damage and apply INFERNO II.",
chargedA: "Deal damage [Based on enemy target's buffs], apply INFERNO III and BLOCK BUFF.",
cooldown: "3",
passiveM: "Every turn: gain OVERLOAD. On kill: lose OVERLOAD. On debuff applications: Gain MARAUDER RAGE II.",
        hp: 14467,
        attack: 5228,
        defense: 1920,
        hacking: 98,
        security: 0,
        critR: 23,
        critD: 42,
        speed: 90  
    },
    {
        name: "Cinya",
        image: "images/chars/cinya.png",
        affinity: "Antimatter",
        rarity: "Rare",
        faction: "Terran Combine",
        role: "Defender",
        basic: "",
        charged: "attack down 2",
        passive: "repair self",
        refit: "",
        basicA: "Deal damage [Based on def].",
chargedA: "Deal damage [Based on def] and apply ATTACK DOWN II.",
cooldown: "2",
passiveM: "Every turn: Repair self",
        hp: 17923,
        attack: 2916,
        defense: 3833,
        hacking: 88,
        security: 65,
        critR: 0,
        critD: 20,
        speed: 60  
    },
    {
        name: "Crocus",
        image: "images/chars/crocus.png",
        affinity: "Thermal",
        rarity: "Legendary",
        faction: "Gelecek",
        role: "Debuffer",
        basic: ["corrosion 2", "stasis"],
        charged: "detonate corrosion",
        passive: "repair self",
        refit: "corrosion 2",
        basicA: "Deal damage and apply CORROSION II. If enemy has >3 debuffs: Apply STASIS.",
chargedA: "Deal damage and detonate corrosion.",
cooldown: "4",
passiveM: "When allies apply corrosion to an enemy: Repair self and apply CORROSION II.",
        hp: 15977,
        attack: 4651,
        defense: 2381,
        hacking: 151,
        security: 16,
        critR: 4,
        critD: 18,
        speed: 89  
    },
    {
        name: "Crucialis",
        image: "images/chars/crucialis.png",
        affinity: "Electric",
        rarity: "Rare",
        faction: "GelecAtlas Syndicate",
        role: "Attacker",
        basic: "bypass shield",
        charged: "bypass shield",
        passive: ["shield", "atlas coordination 2"],
        refit: "",
        basicA: "Deal damage [Bypass shield]. When critical, additionally: Deal damage [Bypass shield].",
chargedA: "Deal damage [Bypass shield]. When critical, additionally: Deal damage [Bypass shield].",
cooldown: "2",
passiveM: "Start of combat: Gain shield and gain ATLAS COORDINATION II.",
        hp: 13366,
        attack: 4397,
        defense: 1537,
        hacking: 90,
        security: 17,
        critR: 17,
        critD: 46,
        speed: 85  
    },
    {
      name: "Cultivator",
      image: "images/chars/cultivator.png",
      affinity: "Chemical",
      rarity: "Legendary",
      faction: "Binderburg",
      role: "Supporter",
      basic: ["defense up 3","remove debuff"],
      charged: ["inc. damage down 3", "binderburg resilience 3", "remove debuff"],
      passive: "repair self",
      refit: "repair",
      basicA: "Apply DEFENSE UP III and remove 1 debuff.",
chargedA: "Apply INC. DAMAGE DOWN III, apply BINDERBURG RESILIENCE III and remove 1 debuff.",
cooldown: "3",
passiveM: "When self removes a debuff: Apply repair. Ally or self damaged (except dots): Apply repair.",
      hp: 22413,
      attack: 1770,
      defense: 3265,
      hacking: 99,
      security: 73,
      critR: 4,
      critD: 20,
      speed: 95  
  },
  {
    name: "Curator",
    image: "images/chars/curator.png",
    affinity: "Chemical",
    rarity: "Legendary",
    faction: "Binderburg",
    role: "Debuffer",
    basic: "attack down 3",
    charged: "out. damage down 3",
    passive: "",
    refit: "security down 3",
    basicA: "Deal damage and apply ATTACK DOWN III.",
chargedA: "Deal damage and apply OUT. DAMAGE DOWN II.",
cooldown: "4",
passiveM: "When an enemy uses their charged active: Deal damage and apply SECURITY DOWN II.",
    hp: 19033,
    attack: 4562,
    defense: 2262,
    hacking: 152,
    security: 24,
    critR: 2,
    critD: 30,
    speed: 77  
  },  
  {
    name: "Defiant",
    image: "images/chars/defiant.png",
    affinity: "Chemical",
    rarity: "Epic",
    faction: "Frontier Legion",
    role: "Defender",
    basic: "provoke",
    charged: "stasis",
    passive: "shield",
    refit: "",
    basicA: "Deal damage and apply PROVOKE.",
chargedA: "Deal damage and apply STASIS.",
cooldown: "2",
passiveM: "When this ship applies stasis: Gain shield. When adjacent to supporter: Gain 20% HP.",
    hp: 21534,
    attack: 3362,
    defense: 4261,
    hacking: 85,
    security: 54,
    critR: 7,
    critD: 12,
    speed: 71  
  },
  {
    name: "Demolisher",
    image: "images/chars/demolisher.png",
    affinity: "Antimatter",
    rarity: "Legendary",
    faction: "Marauders",
    role: "Attacker",
    basic: "bomb 3",
    charged: "detonate bomb",
    passive: "",
    refit: ["bypass shield", "bypass defense"],
    basicA: "Deal damage and apply BOMB III.",
chargedA: "Deal damage and detonate bomb.",
cooldown: "3",
passiveM: "When a bomb explodes on an enemy: Lose charge on that enemy and deal damage [Bypass defense][Bypass shield] to units adjacent to enemy.",
    hp: 13366,
    attack: 5535,
    defense: 2593,
    hacking: 103,
    security: 1,
    critR: 28,
    critD: 34,
    speed: 95  
  },
  {
    name: "Faust",
    image: "images/chars/faust.png",
    affinity: "Thermal",
    rarity: "Rare",
    faction: "Everliving",
    role: "Supporter",
    basic: ["repair","security up 2"],
    charged: ["repair", "everliving regeneration 2", "defense up 2"],
    passive: "remove buff",
    refit: "",
    basicA: "Repair and apply SECURITY UP II.",
chargedA: "Repair, apply EVERLIVING REGENERATION II and DEFENSE UP II.",
cooldown: "2",
passiveM: "On death: Remove 3 buffs on that enemy.",
    hp: 11907,
    attack: 1536,
    defense: 3001,
    hacking: 91,
    security: 62,
    critR: 5,
    critD: 20,
    speed: 95  
  },
  {
    name: "Flamel",
    image: "images/chars/flamel.png",
    affinity: "Antimatter",
    rarity: "Epic",
    faction: "Everliving",
    role: "Supporter",
    basic: ["repair", "repair over time"],
    charged: ["repair", "repair over time 2"],
    passive: "speed down",
    refit: "stasis",
    basicA: "Repair and apply REPAIR OVER TIME I.",
chargedA: "Repair and apply REPAIR OVER TIME II.",
cooldown: "2",
passiveM: "When damaged: Apply SPEED DOWN I to that enemy and apply STASIS.",
    hp: 17650,
    attack: 1666,
    defense: 3121,
    hacking: 93,
    security: 56,
    critR: 7,
    critD: 20,
    speed: 97  
  },
  {
    name: "Fronline",
    image: "images/chars/frontline.png",
    affinity: "Electric",
    rarity: "Legendary",
    faction: "Atlas Syndicate",
    role: "Attacker",
    basic: ["shield", "bypass shield"],
    charged: "lose charge",
    passive: "attack up 3",
    refit: "fill charge",
basicA: "Deal damage [Bypass shield]. If any targets have shield: Gain shield.",
chargedA: "Deal damage [Bypass shield] and lose charge.",
cooldown: "4",
passiveM: "After damaging, an enemy with the affinity advantage bonus: Gain ATTACK UP III and fill charge.",
    hp: 10471,
    attack: 5413,
    defense: 2328,
    hacking: 109,
    security: 12,
    critR: 16,
    critD: 62,
    speed: 84  
  },
  {
    name: "Gallant",
    image: "images/chars/gallant.png",
    affinity: "Thermal",
    rarity: "Rare",
    faction: "Frontier Legion",
    role: "Attacker",
    basic: "",
    charged: "stasis",
    passive: "legion discipline 2",
    refit: "",
    basicA: "Deal damage. When attacking a defender, instead: Deal damage.",
chargedA: "Deal damage. When attacking a defender, instead: Deal damage and apply STASIS.",
cooldown: "2",
passiveM: "On kill: gain LEGION DISCIPLINE II.",
    hp: 13366,
    attack: 5105,
    defense: 2473,
    hacking: 95,
    security: 14,
    critR: 8,
    critD: 46,
    speed: 86  
  },
  {
    name: "Grif",
    image: "images/chars/grif.png",
    affinity: "Chemical",
    rarity: "Legendary",
    faction: "Xaoc",
    role: "Supporter",
    basic: ["out. damage up 3", "hacking up 3"],
    charged: ["crit damage up 3", "attack up 3"],
    passive: "",
    refit: "disable",
    basicA: "Apply OUT. DAMAGE UP II to all allies and apply HACKING UP III.",
chargedA: "Apply CRIT DMG UP III to all allies and apply ATTACK UP III.",
cooldown: "4",
passiveM: "When an enemy cleanses a debuff: Deal damage and apply DISABLE.",
    hp: 16809,
    attack: 3463,
    defense: 2808,
    hacking: 92,
    security: 62,
    critR: 18,
    critD: 34,
    speed: 97  
  },
  {
    name: "Harvester",
    image: "images/chars/harvester.png",
    affinity: "Electric",
    rarity: "Rare",
    faction: "Binderbug",
    role: "Supporter",
    basic: ["crit rate up 2", "attack up 2", "remove debuff"],
    charged: ["crit damage up 3", "attack up 3"],
    passive: "",
    refit: "speed up",
    basicA: "Apply CRIT RATE UP II, apply ATTACK UP II and remove 1 debuff.",
chargedA: "Apply CRIT DMG UP III and apply ATTACK UP III.",
cooldown: "2",
passiveM: "When all dies: give extra end of round action and gain SPEED UP I.",
    hp: 16809,
    attack: 3463,
    defense: 2808,
    hacking: 92,
    security: 62,
    critR: 18,
    critD: 34,
    speed: 97  
  },
  {
    name: "Hayyan",
    image: "images/chars/hayyan.png",
    affinity: "Electric",
    rarity: "Legendary",
    faction: "Everliving",
    role: "Supporter",
    basic: ["repair", "hacking up 2", "remove debuff"],
    charged: ["repair", "cheat death","fill charge"],
    passive: "repair",
    refit: "repair",
    basicA: "Apply repair on all allies, apply HACKING UP II and remove 1 debuff.",
chargedA: "Apply repair on all allies, apply CHEAT DEATH and fill charge.",
cooldown: "4",
passiveM: "When self removes a debuff from an ally: apply repair. When an ally is debuffed: Apply repair.",
    hp: 19052,
    attack: 2396,
    defense: 2928,
    hacking: 94,
    security: 65,
    critR: 8,
    critD: 20,
    speed: 98  
  },
  {
    name: "Heliodor",
    image: "images/chars/heliodor.png",
    affinity: "Thermal",
    rarity: "Epic",
    faction: "MPL",
    role: "Supporter",
    basic: ["inc. damage down 2", "defense up 3"],
    charged: ["security up 3", "matrix defense"],
    passive: ["repair", "remove debuff"],
    refit: "",
    basicA: "Apply INC. DAMAGE DOWN II and apply DEFENSE UP III.",
chargedA: "Apply SECURITY UP III and apply DEFENSE MATRIX.",
cooldown: "3",
passiveM: "When damaged (except dots): Expire debuffs on allies and apply repair.",
    hp: 16389,
    attack: 1536,
    defense: 2496,
    hacking: 90,
    security: 69,
    critR: 7,
    critD: 20,
    speed: 92  
  },
  {
    name: "Hermes",
    image: "images/chars/hermes.png",
    affinity: "Thermal",
    rarity: "Legendary",
    faction: "Everliving",
    role: "Supporter",
    basic: "repair",
    charged: ["cheat death", "fill charge", "repair"],
    passive: "fill charge",
    refit: "everliving regeneration",
    basicA: "Repair.",
chargedA: "If target has <40% hp: apply CHEAT DEATH. Additionally: Fill charge and apply REPAIR.",
cooldown: "6",
passiveM: "When all ally crits an enemy: Fill charge and apply EVERLIVING REGENERATION II to that ally.",
    hp: 22699,
    attack: 1927,
    defense: 3361,
    hacking: 94,
    security: 61,
    critR: 8,
    critD: 36,
    speed: 85  
  },
  {
    name: "Huanying",
    image: "images/chars/huanying.png",
    affinity: "Thermal",
    rarity: "Rare",
    faction: "Tianchao",
    role: "Debuffer",
    basic: "bomb",
    charged: ["concentrate fire", "bomb 2"],
    passive: "stealth",
    refit: "tianchao precision 2",
    basicA: "Deal damage (ignore taunt and provoke) and apply BOMB I.",
chargedA: "Deal damage (ignore taunt and provoke), apply CONCENTRATE FIRE and BOMB II.",
cooldown: "3",
passiveM: "When this ship applies a debuff: Gain STEALTH and gain TIANCHAO PRECISION II.",
    hp: 13338,
    attack: 4441,
    defense: 1405,
    hacking: 143,
    security: 11,
    critR: 5,
    critD: 22,
    speed: 83  
  },
  {
    name: "Ionscorp",
    image: "images/chars/ionscorp.png",
    affinity: "Chemical",
    rarity: "Rare",
    faction: "Atlas Syndicate",
    role: "Attacker",
    basic: "",
    charged: "disable",
    passive: ["shield", "atlas coordination 2"],
    refit: "",
    basicA: "Deal damage.",
chargedA: "Deal damage. When attacking a defender, instead: Deal damage and apply DISABLE.",
cooldown: "1",
passiveM: "Start of combat: Gain shield and gain ATLAS COORDINATION II.",
    hp: 13366,
    attack: 4951,
    defense: 1537,
    hacking: 102,
    security: 17,
    critR: 5,
    critD: 54,
    speed: 81  
  },
  {
    name: "Iridium",
    image: "images/chars/iridium.png",
    affinity: "Antimatter",
    rarity: "Legendary",
    faction: "MPL",
    role: "Defender",
    basic: ["repair self", "bypass shield"],
    charged: ["disable", "bypass shield"],
    passive: "",
    refit: "speed down 2",
    basicA: "Deal damage [Bypass shield] and repair self.",
chargedA: "Deal damage [Bypass shield] and apply DISABLE.",
cooldown: "3",
passiveM: "This ship takes less damage from critical hits. When damaged (except dots): Apply SPEED DOWN II to that enemy .",
    hp: 28825,
    attack: 2396,
    defense: 3857,
    hacking: 123,
    security: 41,
    critR: 1,
    critD: 4,
    speed: 63  
  },
  {
    name: "Judge",
    image: "images/chars/judge.png",
    affinity: "Electric",
    rarity: "Legendary",
    faction: "Frontier Legion",
    role: "Attacker",
    basic: ["concentrate fire", "bypass defense"],
    charged: "bypass defense",
    passive: "",
    refit: "",
    basicA: "Deal damage (ignore taunt and provoke) [Bypass defense] and apply CONCENTRATE FIRE.",
chargedA: "Deal damage (ignore taunt and provoke) [Bypass defense].",
cooldown: "3",
passiveM: "Damage increased for each dead  enemy. Start of round: Deal damage.",
    hp: 12952,
    attack: 6119,
    defense: 1969,
    hacking: 98,
    security: 9,
    critR: 19,
    critD: 54,
    speed: 94  
  },
  {
    name: "Kafa",
    image: "images/chars/kafa.png",
    affinity: "Chemical",
    rarity: "Rare",
    faction: "Terran Combine",
    role: "Defender",
    basic: ["defense down", "bypass defense"],
    charged: ["defense down 2", "provoke", "bypass defense"],
    passive: "terran tenacity",
    refit: "terran tenacity 2",
    basicA: "Deal damage [Bypass defense] and apply DEFENSE DOWN I.",
chargedA: "Deal damage [Bypass defense], apply DEFENSE DOWN II and PROVOKE.",
cooldown: "2",
passiveM: "When HP drops below 50%: Gain TERRAN TENACITY II.",
    hp: 17923,
    attack: 1846,
    defense: 4261,
    hacking: 88,
    security: 61,
    critR: 0,
    critD: 20,
    speed: 60  
  },
  {
    name: "Kinetik",
    image: "images/chars/kinetik.png",
    affinity: "Electric",
    rarity: "Rare",
    faction: "Atlas Syndicate",
    role: "Defender",
    basic: "defense down",
    charged: ["defense down 2", "out. damage 2"],
    passive: "shield",
    refit: "",
    basicA: "Deal damage and apply DEFENSE DOWN I.",
chargedA: "Deal damage and apply DEFENSE DOWN II and OUT. DAMAGE DOWN II.",
cooldown: "2",
passiveM: "Every turn: Gain shield.",
    hp: 23341,
    attack: 2530,
    defense: 3643,
    hacking: 90,
    security: 59,
    critR: 2,
    critD: 4,
    speed: 64  
  },
  {
    name: "Laika",
    image: "images/chars/laika.png",
    affinity: "Thermal",
    rarity: "Rare",
    faction: "Xaoc",
    role: "Defender",
    basic: "remove debuff",
    charged: "bypass defense",
    passive: "shield",
    refit: "",
    basicA: "Remove 1 debuff and deal damage.",
chargedA: "Deal damage [Bypass defense].",
cooldown: "2",
passiveM: "When this ship removes a shield: Gain shield.",
    hp: 21256,
    attack: 3125,
    defense: 3571,
    hacking: 79,
    security: 41,
    critR: 12,
    critD: 34,
    speed: 72  
  },
  {
    name: "Larkspur",
    image: "images/chars/larkspur.png",
    affinity: "Electric",
    rarity: "Rare",
    faction: "Gelecek",
    role: "Debuffer",
    basic: "inc. repair down 2",
    charged: ["inc. damage up 2", "inc. repair down 3"],
    passive: "gelecek contagion 2",
    refit: "",
    basicA: "Deal damage and apply INC. REPAIR DOWN II",
chargedA: "Deal damage and apply INC. DAMAGE III and INC. DAMAGE UP II.",
cooldown: "3",
passiveM: "When enemy cleanses a debuff: Gain GELECEK CONTAGION II.",
    hp: 13893,
    attack: 4201,
    defense: 2881,
    hacking: 148,
    security: 17,
    critR: 0,
    critD: 2,
    speed: 78  
  },
  {
    name: "Liberator",
    image: "images/chars/liberator.png",
    affinity: "Thermal",
    rarity: "Legendary",
    faction: "Frontier Legion",
    role: "Attacker",
    basic: "bypass shield",
    charged: ["bypass shield", "legion discipline 3"],
    passive: "fill charge",
    refit: "extra action",
    basicA: "Deal damage [Bypass shield].",
chargedA: "Apply LEGION DISCIPLINE III to all allies and deal damage [Bypass shield].",
cooldown: "2",
passiveM: "When enemy dies: Fill charge on all allies and give extra action.",
    hp: 15432,
    attack: 5566,
    defense: 2401,
    hacking: 86,
    security: 9,
    critR: 23,
    critD: 54,
    speed: 94  
  },
  {
    name: "Los",
    image: "images/chars/los.png",
    affinity: "Electric",
    rarity: "Legendary",
    faction: "Xaoc ",
    role: "Attacker",
    basic: "",
    charged: "xaoc swiftness 3",
    passive: "block damage",
    refit: "fill charge",
    basicA: "Deal damage",
chargedA: "Apply XAOC SWIFTNESS III to all allies and deal damage.",
cooldown: "3",
passiveM: "When HP drops under 50%, once per battle apply BLOCK DAMAGE. While HP is below 50% increase out. damage by 30%. Start of combat: Fill charge.",
    hp: 10885,
    attack: 6028,
    defense: 2689,
    hacking: 102,
    security: 9,
    critR: 18,
    critD: 60,
    speed: 84  
  },
  {
    name: "Luxx",
    image: "images/chars/luxx.png",
    affinity: "Antimatter",
    rarity: "Epic",
    faction: "Atlas Syndicate ",
    role: "Attacker",
    basic: "bypass shield",
    charged: ["bypass shield", "atlas coordination 2"],
    passive: "blast",
    refit: "shield",
    basicA: "Deal damage [Bypass shield].",
chargedA: "Gain ATLAS COORDINATION II and deal damage [Bypass shield].",
cooldown: "3",
passiveM: "Every turn until 4 charges are reached: Gain BLAST. Every turn gain shield.",
    hp: 11574,
    attack: 5105,
    defense: 2088,
    hacking: 92,
    security: 19,
    critR: 15,
    critD: 62,
    speed: 83  
  },
  {
    name: "Madax",
    image: "images/chars/madax.png",
    affinity: "Electric",
    rarity: "Legendary",
    faction: "Terran Combine",
    role: "Defender",
    basic: "taunt",
    charged: "terran bolster",
    passive: "repair self",
    refit: "",
    basicA: "Gain TAUNT deal damage [Based on def].",
chargedA: "Apply TERRAN BOLSTER to all allies and deal damage [Based on def].",
cooldown: "3",
passiveM: "When enemy dies: Repair self. When adjacent to a supporter: Receive more repair. Increase that supporter's defense by 20% of this ship's defense.",
    hp: 22486,
    attack: 2474,
    defense: 4619,
    hacking: 91,
    security: 68,
    critR: 5,
    critD: 12,
    speed: 68  
  },
  {
    name: "Magnolia",
    image: "images/chars/magnolia.png",
    affinity: "Electric",
    rarity: "Rare",
    faction: "Gelecek",
    role: "Attacker",
    basic: "inferno",
    charged: "inferno 2",
    passive: "repair self",
    refit: "",
    basicA: "Deal damage and apply INFERNO I.",
chargedA: "Deal damage and apply INFERNO II.",
cooldown: "1",
passiveM: "When this ship damages enemy: Repair self.",
    hp: 13778,
    attack: 4767,
    defense: 2473,
    hacking: 105,
    security: 5,
    critR: 3,
    critD: 26,
    speed: 92  
  },
  {
    name: "Mangler",
    image: "images/chars/mangler.png",
    affinity: "Chemical",
    rarity: "Rare",
    faction: "Marauders",
    role: "Attacker",
    basic: "bomb",
    charged: "bomb 2",
    passive: ["overload", "marauder rage 2"],
    refit: "",
    basicA: "Deal damage and apply BOMB I.",
chargedA: "Deal damage and apply BOMB II.",
cooldown: "2",
passiveM: "Every turn: Gain OVERLOAD. On kill: Lose OVERLOAD and gain MARAUDER RAGE II.",
    hp: 11298,
    attack: 5074,
    defense: 1800,
    hacking: 96,
    security: 2,
    critR: 25,
    critD: 34,
    speed: 92  
  },
  {
    name: "Medved",
    image: "images/chars/medved.png",
    affinity: "Thermal",
    rarity: "Rare",
    faction: "Xaoc",
    role: "Attacker",
    basic: "bypass shield",
    charged: ["bypass shield", "stasis"],
    passive: "xaoc swiftness 2",
    refit: "",
    basicA: "Deal damage [Bypass shield].",
chargedA: "Deal damage [Bypass shield] and apply STASIS.",
cooldown: "2",
passiveM: "On kill: Gain XAOC SWIFTNESS II.",
    hp: 11298,
    attack: 5566,
    defense: 2328,
    hacking: 99,
    security: 2,
    critR: 11,
    critD: 68,
    speed: 81  
  },
  {
    name: "Meiying",
    image: "images/chars/meiying.png",
    affinity: "Thermal",
    rarity: "Legendary",
    faction: "Tianchao",
    role: "Attacker",
    basic: "",
    charged: "stasis",
    passive: "stasis",
    refit: "stealth",
    basicA: "Deal damage (ignore taunt and provoke). When attacking a supporter, additionally deal extra damage.",
chargedA: "Deal damage (ignore taunt and provoke) and apply STASIS. When attacking supporter additionally deal extra damage.",
cooldown: "2",
passiveM: "When this ships kills an enemy that has a debuff: Apply STASIS to adjacent enemies. Start of combat and every turn: Gain STEALTH.",
    hp: 15294,
    attack: 6028,
    defense: 2208,
    hacking: 111,
    security: 2,
    critR: 14,
    critD: 46,
    speed: 92  
  },
  {
    name: "Morao",
    image: "images/chars/morao.png",
    affinity: "Thermal",
    rarity: "Epic",
    faction: "Terran Combine",
    role: "Defender",
    basic: "provoke",
    charged: "remove debuff",
    passive: "repair self",
    refit: "defense up 2",
    basicA: "Deal damage [Based on def] and apply provoke.",
chargedA: "Remove 2 debuffs and deal damage [Based on def].",
cooldown: "2",
passiveM: "Every turn: Repair self. When self removes a debuff: Repair self and gain DEFENSE UP II.",
    hp: 18617,
    attack: 2213,
    defense: 4446,
    hacking: 90,
    security: 67,
    critR: 4,
    critD: 20,
    speed: 62  
  },
  {
    name: "Nemesis",
    image: "images/chars/nemesis.png",
    affinity: "Chemical",
    rarity: "Epic",
    faction: "Atlas Syndicate",
    role: "Defender",
    basic: "attack down 2",
    charged: ["atlas readiness 2", "attack down 3"],
    passive: "warding screen",
    refit: "shield",
    basicA: "Deal damage and apply ATTACK DOWN II.",
chargedA: "Gain ATTACK READINESS II, deal damage and apply ATTACK DOWN III.",
cooldown: "2",
passiveM: "Every turn, until 4 charges of WARDING SCREEN are reached: Gain WARDING SCREEN. Every turn: Gain shield.",
    hp: 19033,
    attack: 2344,
    defense: 3762,
    hacking: 126,
    security: 61,
    critR: 0,
    critD: 12,
    speed: 66  
  },
  {
    name: "Nosorog",
    image: "images/chars/nosorog.png",
    affinity: "Chemical",
    rarity: "Epic",
    faction: "Xaoc",
    role: "Defender",
    basic: "",
    charged: "remove debuff",
    passive: ["bypass defense", "counter attack"],
    refit: "defense up 2",
    basicA: "Deal damage.",
chargedA: "Deal damage and remove 1 buff.",
cooldown: "1",
passiveM: "When damaged: Deal damage [No critical, Bypass defense].When self removes a debuff: Gain DEFENSE UP II.",
    hp: 22486,
    attack: 2474,
    defense: 4619,
    hacking: 91,
    security: 68,
    critR: 5,
    critD: 12,
    speed: 68  
  },
  {
    name: "Nuqtu",
    image: "images/chars/nuqtu.png",
    affinity: "Electric",
    rarity: "Legendary",
    faction: "Terran Combine",
    role: "Attacker",
    basic: "fill charge",
    charged: "extra action",
    passive: "repair self",
    refit: "core charge",
    basicA: "Deal damage ( based on number of target's buffs). If target has > 2 buffs: Fill charge.",
chargedA: "Deal damage [Based on number of target's buffs]. If target has > 2 buffs: Give extra end round action.",
cooldown: "5",
passiveM: "When an enemy gets buffed: Repair self and gain CORE CHARGE I.",
    hp: 12539,
    attack: 5259,
    defense: 3384,
    hacking: 95,
    security: 18,
    critR: 16,
    critD: 62,
    speed: 84  
  },
  {
    name: "Obsidian",
    image: "images/chars/obsidian.png",
    affinity: "Thermal",
    rarity: "Legendary",
    faction: "MPL",
    role: "Attacker",
    basic: "remove buff",
    charged: "",
    passive: "fill charge",
    refit: "attack up 3",
    basicA: "Remove 1 buff and deal damage [Based on max HP].",
chargedA: "Deal damage [Based on max HP]. Deal more damage to low health enemies.",
cooldown: "3",
passiveM: "On kill: Fill charge. When self removes a buff gain: ATACK UP III.",
    hp: 19290,
    attack: 5720,
    defense: 2184,
    hacking: 105,
    security: 21,
    critR: 16,
    critD: 64,
    speed: 76  
  },
  {
    name: "Opal",
    image: "images/chars/opal.png",
    affinity: "Electric",
    rarity: "Epic",
    faction: "MPL",
    role: "Defender",
    basic: ["repair self", "bypass shield"],
    charged: ["bypass shield", "lose charge"],
    passive: "attack down 2",
    refit: "defense up 2",
    basicA: "Deal damage [Based on max HP] and repair self",
chargedA: "Deal damage [Based on max HP] and lose charge.",
cooldown: "3",
passiveM: "When damaged (except DoTs): Apply ATTACK DOWN II to that enemy and gain DEFENSE UP II.",
    hp: 25425,
    attack: 2441,
    defense: 3191,
    hacking: 92,
    security: 66,
    critR: 0,
    critD: 4,
    speed: 66  
  },
  {
    name: "Panguan",
    image: "images/chars/panguan.png",
    affinity: "Chemical",
    rarity: "Legendary",
    faction: "Tianchao",
    role: "Attacker",
    basic: "bomb 2",
    charged: "bomb 3",
    passive: "stealth",
    refit: "",
    basicA: "Deal damage [Based on number of ships adjacent to target] and apply BOMB II.",
chargedA: "Deal damage [Based on number of ships adjacent to target] and apply BOMB III",
cooldown: "3",
passiveM: "Friendly stealthed units deal 40% more damage. When damaged (except DoTs): Gain STEALTH.",
    hp: 12814,
    attack: 5473,
    defense: 1776,
    hacking: 115,
    security: 2,
    critR: 18,
    critD: 54,
    speed: 87  
  },
  {
    name: "Panon",
    image: "images/chars/panon.png",
    affinity: "Thermal",
    rarity: "Legendary",
    faction: "Terran Combine",
    role: "Defender",
    basic: ["terran guard 2", "terran guard 3"],
    charged: "block attacks",
    passive: ["block attacks", "barrier recharging"],
    refit: "",
    basicA: "Apply TERRAN GUARD II to all alies and deal damage [Based on def]. If provoked or taunted, instead: Apply TERRAN GUARD III and deal damage [Based on def].",
chargedA: "Deal damage [Based on def]. If provoked or taunted, instead: Gain BLOCK ATTACKS and dead damage [Based on def]",
cooldown: "3",
passiveM: "When damaged (except DoTs): Gain BLOCK ATTACKS and gain BARRIER RECHARGING: Reduce incoming damage by 20%.",
    hp: 25297,
    attack: 2474,
    defense: 4619,
    hacking: 91,
    security: 64,
    critR: 5,
    critD: 4,
    speed: 71  
  },
  {
    name: "Paracelsus",
    image: "images/chars/paracelsus.png",
    affinity: "Chemical",
    rarity: "Rare",
    faction: "Everliving",
    role: "Supporter",
    basic: ["attack up 2", "crit damage up 2"],
    charged: ["attack up 3", "crit damage up 3", "remove debuff"],
    passive: "",
    refit: "everliving regeneration 2",
    basicA: "Apply ATTACK UP II and CRIT DAMAGE UP II.",
chargedA: "Apply ATTACK UP III, CRIT DAMAGE UP III and remove 2 debuffs.",
cooldown: "2",
passiveM: "On death: Deal damage [Based on max HP] and apply EVERLIVING REGENERATION II to all allies.",
    hp: 14428,
    attack: 1536,
    defense: 3433,
    hacking: 91,
    security: 50,
    critR: 5,
    critD: 20,
    speed: 95  
  },
  {
    name: "Prospect",
    image: "images/chars/prospect.png",
    affinity: "Chemical",
    rarity: "Rare",
    faction: "MPL",
    role: "Defender",
    basic: "attack down",
    charged: ["attack down 2", "defense down 2"],
    passive: "inc. damage down 2",
    refit: "",
    basicA: "Deal damage [Based on max HP] and apply ATTACK DOWN I.",
chargedA: "Deal damage [Based on max HP] and apply ATTACK DOWN II and DEFENSE DOWN II.",
cooldown: "2",
passiveM: "When this ship applies debuff: Gain INC. DAMAGE DOWN II.",
    hp: 24730,
    attack: 2292,
    defense: 3071,
    hacking: 91,
    security: 68,
    critR: 5,
    critD: 12,
    speed: 68  
  },
  {
    name: "Purifier",
    image: "images/chars/purifier.png",
    affinity: "Chemical",
    rarity: "Rare",
    faction: "Binderburg",
    role: "Supporter",
    basic: ["hacking up 2", "binderburg resilience 2","remove debuff"],
    charged: ["hacking up 3", "security up 3"],
    passive: "remove debuff",
    refit: "",
    basicA: "Deal damage and apply INFERNO I.",
basicA: "Apply HACKING UP II, BINDERBURG RESILIENCE II and remove 1 debuff.",
chargedA: "Apply HACKING UP III and SECURITY UP III.",
cooldown: "2",
passiveM: "When damaged: Remove 2 debuffs",
    hp: 17790,
    attack: 1380,
    defense: 2905,
    hacking: 96,
    security: 70,
    critR: 1,
    critD: 20,
    speed: 87  
  },
  {
    name: "Ravager",
    image: "images/chars/ravager.png",
    affinity: "Chemical",
    rarity: "Legendary",
    faction: "Marauders",
    role: "Attacker",
    basic: "inferno",
    charged: "inferno 3",
    passive: ["overload", "marauder rage 3"],
    refit: ["hacking up 2", "out. damage up 2"],
    basicA: "Deal damage and apply INFERNO I.",
chargedA: "Deal damage [Based on number of target's debuff] and apply INFERNO III.",
cooldown: "2",
passiveM: "Every turn: Gain Overload. On kill: Lose Overload and gain MARAUDER RAGE III. When this ship's debuff is resisted: Gain HACKING UP II and OUT. DAMAGE UP II.",
    hp: 15845,
    attack: 6088,
    defense: 2161,
    hacking: 95,
    security: 1,
    critR: 28,
    critD: 34,
    speed: 95  
  },
  {
    name: "Redeemer",
    image: "images/chars/redeemer.png",
    affinity: "Thermal",
    rarity: "Rare",
    faction: "Frontier Legion",
    role: "Defender",
    basic: "",
    charged: "legion discipline 2",
    passive: "shield",
    refit: "defense up 3",
    basicA: "Deal damage.",
chargedA: "Gain LEGION DISCIPLINE II and deal damage.",
cooldown: "2",
passiveM: "Every turn: Gain shield.When HP drops below 60%: Apply DEFENSE UP III. ",
    hp: 18339,
    attack: 2344,
    defense: 4178,
    hacking: 83,
    security: 56,
    critR: 1,
    critD: 12,
    speed: 69  
  },
  {
    name: "Refine",
    image: "images/chars/refine.png",
    affinity: "Electric",
    rarity: "Rare",
    faction: "MPL",
    role: "Supporter",
    basic: ["supercharged", "hacking up"],
    charged: ["supercharged 3", "hacking up 3"],
    passive: "inc. damage down",
    refit: "",
    basicA: "Apply SUPERCHARGED I and HACKING UP I.",
chargedA: "Apply SUPERCHARGED III and HACKING UP II.",
cooldown: "2",
passiveM: "Ally damaged: Apply INC. DAMAGE I.",
    hp: 15689,
    attack: 1406,
    defense: 2808,
    hacking: 96,
    security: 71,
    critR: 5,
    critD: 20,
    speed: 90  
  },
  {
    name: "Rikra",
    image: "images/chars/rikra.png",
    affinity: "Thermal",
    rarity: "Rare",
    faction: "Terran Combine",
    role: "Attacker",
    basic: "",
    charged: "defense up 2",
    passive: "repair self",
    refit: "",
    basicA: "Deal damage. When hitting taunt or provoke: Additionally deal damage.",
chargedA: "Gain DEFENSE UP II. When hitting taunt or provoke: Additionally deal damage.",
cooldown: "2",
passiveM: "On kill: Repair self.",
    hp: 12952,
    attack: 4798,
    defense: 2161,
    hacking: 92,
    security: 19,
    critR: 13,
    critD: 54,
    speed: 77  
  },
  {
    name: "Ripper",
    image: "images/chars/ripper.png",
    affinity: "Electric",
    rarity: "Epic",
    faction: "Marauders",
    role: "Debuffer",
    basic: "inc. repair down 2",
    charged: "inc. repair down 3",
    passive: "marauder rage 2",
    refit: "extend buff",
    basicA: "Deal damage and apply INC. REPAIR DOWN II.",
chargedA: "Deal damage and apply INC. REPAIR DOWN III.",
cooldown: "3",
passiveM: "On debuff application: Gain MARAUDER RAGE II and extend buffs on all allies.",
    hp: 12087,
    attack: 4112,
    defense: 2333,
    hacking: 137,
    security: 12,
    critR: 13,
    critD: 10,
    speed: 88  
  },
  {
    name: "Rys",
    image: "images/chars/rys.png",
    affinity: "Chemical",
    rarity: "Rare",
    faction: "Xaoc",
    role: "Attacker",
    basic: "",
    charged: ["hacking up 3", "speed down 2"],
    passive: "xaoc swiftness 2",
    refit: "",
    basicA: "Deal damage.",
chargedA: "Gain HACKING UP III, deal damage and apply SPEED DOWN II.",
cooldown: "3",
passiveM: "When damaging a supporter/defender: Gain XAOC SWIFTNESS II.",
    hp: 8818,
    attack: 5012,
    defense: 2328,
    hacking: 99,
    security: 10,
    critR: 7,
    critD: 60,
    speed: 85  
  },
  {
    name: "Salvation",
    image: "images/chars/salvation.png",
    affinity: "Chemical",
    rarity: "Epic",
    faction: "Binderburg",
    role: "Supporter",
    basic: ["repair", "binderburg resilience 2"],
    charged: ["repair", "inc. damage down 2"],
    passive: "repair",
    refit: "",
    basicA: "Repair and apply BINDERBURG RESILIENCE II.",
chargedA: "Repair and apply INC. DAMAGE DOWN II.",
cooldown: "2",
passiveM: "On death apply repair on all allies.When a buff is removed from an ally: Apply repair.",
    hp: 18490,
    attack: 1510,
    defense: 3025,
    hacking: 98,
    security: 68,
    critR: 3,
    critD: 20,
    speed: 94  
  },
  {
    name: "Sansi",
    image: "images/chars/sansi.png",
    affinity: "Chemical",
    rarity: "Legendary",
    faction: "Tianchao",
    role: "Defender",
    basic: "defense up",
    charged: "provoke",
    passive: ["block repair", "repair self"],
    refit: "fill charge",
    basicA: "Gain DEFENSE UP I and deal damage.",
chargedA: "Deal damage and apply provoke.",
cooldown: "3",
passiveM: "When damaged: Apply BLOCK REPAIR on that enemy. Enemy repaired (except HoTs): Repair self. Start of combat: Fill charge.",
    hp: 25285,
    attack: 3125,
    defense: 4366,
    hacking: 95,
    security: 52,
    critR: 7,
    critD: 12,
    speed: 82  
  },
  {
    name: "Sebufa",
    image: "images/chars/sebufa.png",
    affinity: "Chemical",
    rarity: "Epic",
    faction: "Terran Combine",
    role: "Attacker",
    basic: "remove buff",
    charged: "lose charge",
    passive: "repair self",
    refit: "remove buff",
    basicA: "Deal damage and remove 1 buff.",
chargedA: "Deal damage and lose charge.",
cooldown: "2",
passiveM: "When self removes a buff from enemy: Repair self and remove 1 buff.",
    hp: 11160,
    attack: 5504,
    defense: 2713,
    hacking: 94,
    security: 17,
    critR: 15,
    critD: 54,
    speed: 83  
  },
  {
    name: "Sentinel",
    image: "images/chars/sentinel.png",
    affinity: "Thermal",
    rarity: "Legendary",
    faction: "Frontier Legion",
    role: "Supporter",
    basic: ["attack up 3", "crit rate up 3", "legion discipline 3"],
    charged: ["out. damage up 3", "crit damage up 3"],
    passive: "",
    refit: "repair",
    basicA: "Apply ATTACK UP III, CRIT RATE UP III and LEGION DISCIPLINE III",
chargedA: "Apply OUT. DAMAGE UP and III CRIT DAMAGE UP III.",
cooldown: "2",
passiveM: "When an ally crits an enemy: Deal damage and apply repair on that ally.",
    hp: 16389,
    attack: 3542,
    defense: 3384,
    hacking: 84,
    security: 58,
    critR: 15,
    critD: 20,
    speed: 103  
  },
  {
    name: "Sha Xing",
    image: "images/chars/sha_xing.png",
    affinity: "Thermal",
    rarity: "Epic",
    faction: "Tianchao",
    role: "Attacker",
    basic: ["inc. repair down 2", "bomb"],
    charged: ["inc. repair down 2", "bomb 3"],
    passive: "stealth",
    refit: "tianchao precision 2",
    basicA: "Deal damage and apply INC. REPAIR DOWN II and BOMB I.",
chargedA: "Deal damage and apply INC. REPAIR DOWN III and BOMB III.",
cooldown: "3",
passiveM: "When damaging a supporter/defender gain: STEALTH. When damaging a debuffed enemy: Gain TIANCHAO PRECISION II.",
    hp: 13916,
    attack: 5166,
    defense: 1969,
    hacking: 110,
    security: 5,
    critR: 9,
    critD: 46,
    speed: 95  
  },
  {
    name: "Shashou",
    image: "images/chars/shashou.png",
    affinity: "Antimatter",
    rarity: "Rare",
    faction: "Tianchao",
    role: "Attacker",
    basic: "inc. repair down",
    charged: "inc. repair down 2",
    passive: ["stealth", "blast"],
    refit: "",
    basicA: "Deal damage and apply INC. REPAIR DOWN I.",
chargedA: "Deal damage and apply INC. REPAIR DOWN II.",
cooldown: "2",
passiveM: "When damaging a supporter/defender: Gain stealth. Evey turn, until 4 charges of BLAST are reached: Gain BLAST.",
    hp: 13228,
    attack: 5012,
    defense: 2281,
    hacking: 108,
    security: 0,
    critR: 7,
    critD: 46,
    speed: 89  
  },
  {
    name: "Shelter",
    image: "images/chars/shelter.png",
    affinity: "Thermal",
    rarity: "Rare",
    faction: "Binderburg",
    role: "Supporter",
    basic: ["repair", "hacking up"],
    charged: ["repair", "hacking up 2"],
    passive: "block damage",
    refit: "inc. damage down 2",
    basicA: "Repair and apply HACKING UP I.",
chargedA: "Repair and apply HACKING II.",
cooldown: "3",
passiveM: "When HP drops below 20%, once per battle: Apply BLOCK DAMAGE and INC. DAMAGE DOWN II.",
    hp: 18211,
    attack: 1406,
    defense: 2376,
    hacking: 100,
    security: 67,
    critR: 5,
    critD: 20,
    speed: 85  
  },
  {
    name: "Sheperd",
    image: "images/chars/sheperd.png",
    affinity: "Electric",
    rarity: "Rare",
    faction: "Binderburg",
    role: "Defender",
    basic: "repair self",
    charged: "repair self",
    passive: ["corrosion", "attack down"],
    refit: "",
    basicA: "Repair self and deal damage.",
chargedA: "Repair self and deal damage.",
cooldown: "2",
passiveM: "When damaged: Apply CORROSION I to that enemy and apply ATTACK DOWN I.",
    hp: 24314,
    attack: 2262,
    defense: 3595,
    hacking: 86,
    security: 63,
    critR: 0,
    critD: 12,
    speed: 66  
  },
  {
    name: "Snapdragon",
    image: "images/chars/snapdragon.png",
    affinity: "Electric",
    rarity: "Epic",
    faction: "Gelecek",
    role: "Attacker",
    basic: "defense down 2",
    charged: "inc. damage up 2",
    passive: "",
    refit: "",
    basicA: "Apply DEFENSE DOWN II and deal damage.",
chargedA: "Apply INC. DAMAGE UP II and deal damage.",
cooldown: "2",
passiveM: "This ship Crit. Chance and Crit. Damage are increased by 20%.",
    hp: 11987,
    attack: 4920,
    defense: 2161,
    hacking: 119,
    security: 7,
    critR: 21,
    critD: 62,
    speed: 90  
  },
  {
    name: "Sokol",
    image: "images/chars/sokol.png",
    affinity: "Chemical",
    rarity: "Epic",
    faction: "Xaoc",
    role: "Attacker",
    basic: "",
    charged: "extend debuff",
    passive: "blast",
    refit: "extra action",
    basicA: "Deal damage.",
chargedA: "Deal damage and extend debuffs.",
cooldown: "2",
passiveM: "Every turn, until 4 charges of BLAST are reached: Gain BLAST. On kill: Give extra round of action.",
    hp: 11987,
    attack: 5166,
    defense: 2249,
    hacking: 101,
    security: 4,
    critR: 13,
    critD: 68,
    speed: 92  
  },
  {
    name: "Stalwart",
    image: "images/chars/stalwart.png",
    affinity: "Electric",
    rarity: "Epic",
    faction: "Frontier Legion",
    role: "Attacker",
    basic: "concentrate fire",
    charged: "legion discipline 2",
    passive: ["counter attack", "legion discipline 2"],
    refit: "",
    basicA: "Deal damage (ignore taunt and provoke) and apply CONCENTRATE FIRE.",
chargedA: "Apply LEGION DISCIPLINE II to all allies and deal damage (ignore taunt and and provoke).",
cooldown: "2",
passiveM: "When damaged (except DoTs): deal damage and gain LEGION DISCIPLINE II. When adjacent to a supporter: Gain 20% attack.",
    hp: 11574,
    attack: 5259,
    defense: 2593,
    hacking: 97,
    security: 8,
    critR: 14,
    critD: 46,
    speed: 93  
  },
  {
    name: "Sustainer",
    image: "images/chars/sustainer.png",
    affinity: "Chemical",
    rarity: "Legendary",
    faction: "Binderburg",
    role: "Attacker",
    basic: "remove debuff",
    charged: "extra action",
    passive: "out. damage up 3",
    refit: "attack up 3",
    basicA: "Remove 2 debuffs and deal damage [Based on number of buffs].",
chargedA: "Deal damage [based on number of buffs]. If self has no debuffs: Give extra action.",
cooldown: "3",
passiveM: "Start of the round, if self has no debuffs: Gain OUT. DAMAGE UP III. When self removes a debuff: Gain ATTACK UP III.",
    hp: 18876,
    attack: 5136,
    defense: 2713,
    hacking: 109,
    security: 20,
    critR: 12,
    critD: 46,
    speed: 82  
  },
  {
    name: "Torcher",
    image: "images/chars/torcher.png",
    affinity: "Chemical",
    rarity: "Rare",
    faction: "Marauders",
    role: "Debuffer",
    basic: "inferno",
    charged: ["inferno 2", "speed down"],
    passive: "marauder rage",
    refit: "marauder rage 2",
    basicA: "Deal damage and apply INFERNO I.",
chargedA: "Deal damage and apply INFERNO II and SPEED DOWN I.",
cooldown: "2",
passiveM: "On debuff application: Gain MARAUDER RAGE II.",
    hp: 11392,
    attack: 3962,
    defense: 1786,
    hacking: 139,
    security: 10,
    critR: 11,
    critD: 10,
    speed: 82  
  },
  {
    name: "Tycho",
    image: "images/chars/tycho.png",
    affinity: "Thermal",
    rarity: "Rare",
    faction: "Everliving",
    role: "Defender",
    basic: "",
    charged: "provoke",
    passive: ["cheat death", "everliving regeneration 2"],
    refit: "block damage",
    basicA: "Deal damage.",
chargedA: "Deal damage and apply PROVOKE.",
cooldown: "3",
passiveM: "Start of combat: Gain CHEAT DEATH and EVERLIVING REGENERATION II. When HP drops below 40%, once per battle: Apply BLOCK DAMAGE.",
    hp: 20979,
    attack: 2976,
    defense: 3690,
    hacking: 85,
    security: 51,
    critR: 6,
    critD: 4,
    speed: 69  
  },
  {
    name: "Valerian",
    image: "images/chars/valerian.png",
    affinity: "Electric",
    rarity: "Legendary",
    faction: "Gelecek",
    role: "Debuffer",
    basic: "corrosion 2",
    charged: "corrosion 3",
    passive: "repair self",
    refit: "repair",
    basicA: "Deal damage and apply CORROSION II.",
chargedA: "Deal damage and apply CORROSION III.",
cooldown: "2",
passiveM: "On damaging enemy: Apply repair on all allies.",
    hp: 13477,
    attack: 5191,
    defense: 2381,
    hacking: 155,
    security: 24,
    critR: 0,
    critD: 2,
    speed: 81  
  },
  {
    name: "Valiant",
    image: "images/chars/valiant.png",
    affinity: "Electric",
    rarity: "Rare",
    faction: "Frontier Legion",
    role: "Attacker",
    basic: "",
    charged: "legion discipline 2",
    passive: "fill charge",
    refit: "",
    basicA: "Deal damage.",
chargedA: "Gain LEGION DISCIPLINE II and deal damage (based on number of buffs).",
cooldown: "3",
passiveM: "On kill: Fill charge.",
    hp: 13366,
    attack: 5105,
    defense: 2040,
    hacking: 83,
    security: 6,
    critR: 16,
    critD: 54,
    speed: 91  
  },
  {
    name: "Voron",
    image: "images/chars/voron.png",
    affinity: "Chemical",
    rarity: "Legendary",
    faction: "Xaoc",
    role: "Defender",
    basic: "out. damage down",
    charged: "remove buff",
    passive: "damage into dot",
    refit: "",
    basicA: "Deal damage and apply OUT. DAMAGE DOWN I.",
chargedA: "Deal damage and remove 1 buff.",
cooldown: "2",
passiveM: "This ship takes 20%  less damage from DoTs. When damaged, instead: Gain DAMAGE INTO DOT.",
    hp: 23341,
    attack: 3125,
    defense: 3937,
    hacking: 94,
    security: 47,
    critR: 11,
    critD: 35,
    speed: 75  
  },
  {
    name: "Warden",
    image: "images/chars/warden.png",
    affinity: "Thermal",
    rarity: "Epic",
    faction: "Binderbug",
    role: "Defender",
    basic: "provoke",
    charged: "corrosion 2",
    passive: "corrosion",
    refit: "out. damage down 2",
    basicA: "Deal damage and apply PROVOKE.",
chargedA: "Deal damage and apply CORROSION II.",
cooldown: "2",
passiveM: "When damaged (except DoTs): Apply CORROSION I to that enemy and repair self. When self applies a debuff apply OUT. DAMAGE DOWN II.",
    hp: 22507,
    attack: 2411,
    defense: 3286,
    hacking: 104,
    security: 61,
    critR: 0,
    critD: 4,
    speed: 64  
  },
  {
    name: "Xcellence",
    image: "images/chars/xcellence.png",
    affinity: "Chemical",
    rarity: "Legendary",
    faction: "Atlas Syndicate",
    role: "Attacker",
    basic: ["bypass shield","speed down 2"],
    charged: ["bypass shield","disable"],
    passive: "shield",
    refit: "",
    basicA: "Deal damage [Bypass shield] and apply SPEED DOWN II.",
chargedA: "Deal damage [Bypass shield] and apply DISABLE.",
cooldown: "2",
passiveM: "Every turn gain: Shield. When an enemy resists a debuff application: Deal damage.",
    hp: 12952,
    attack: 5966,
    defense: 2328,
    hacking: 109,
    security: 16,
    critR: 12,
    critD: 38,
    speed: 89  
  },
  {
    name: "Yarrow",
    image: "images/chars/yarrow.png",
    affinity: "Antimatter",
    rarity: "Rare",
    faction: "Gelecek",
    role: "Debuffer",
    basic: "corrosion",
    charged: "corrosion 2",
    passive: "gelecek contagion 2",
    refit: "",
    basicA: "Deal damage and apply CORROSION I.",
chargedA: "Deal damage and apply CORROSION II.",
cooldown: "2",
passiveM: "When an enemy cleanses a debuff: Gain GELECEK CONTAGION II.",
    hp: 13893,
    attack: 3861,
    defense: 2023,
    hacking: 148,
    security: 21,
    critR: 0,
    critD: 2,
    speed: 82  
  },
  {
    name: "Yazid",
    image: "images/chars/yazid.png",
    affinity: "Electric",
    rarity: "Epic",
    faction: "Everliving",
    role: "Defender",
    basic: "repair self",
    charged: "everliving regeneration 2",
    passive: ["cheat death", "everliving regeneration 2"],
    refit: "block damage",
    basicA: "Repair self and deal damage.",
chargedA: "Gain EVERLIVING REGENERATION II and deal damage.",
cooldown: "2",
passiveM: "Start of the combat: Gain CHEAT DEATH and EVERLIVING REGENERATION II. On cheat death activation, once per battle: Apply repair self and apply BLOCK DAMAGE.",
    hp: 24175,
    attack: 2266,
    defense: 4285,
    hacking: 91,
    security: 53,
    critR: 4,
    critD: 12,
    speed: 71  
  },
  {
    name: "Yuyan",
    image: "images/chars/yuyan.png",
    affinity: "Chemical",
    rarity: "Epic",
    faction: "Tianchao",
    role: "Debuffer",
    basic: "concentate fire",
    charged: "disable",
    passive: "stealth",
    refit: "tianchao precision 2",
    basicA: "Deal damage (ignore taunt and provoke) and apply CONCENTRATE FIRE.",
chargedA: "Deal damage (ignore taunt and provoke) and apply DISABLE .",
cooldown: "2",
passiveM: "When this ship applies a debuff: Gain STEALTH and TIANCHAO PRECISION II.",
    hp: 11531,
    attack: 5132,
    defense: 1524,
    hacking: 149,
    security: 17,
    critR: 11,
    critD: 30,
    speed: 81  
  },
    {
    name: "Zeolite",
    image: "images/chars/zeolite.png",
    affinity: "Electric",
    rarity: "Legendary",
    faction: "MPL",
    role: "Debuffer",
    basic: ["defense down 3", "remove buff"],
    charged: "emp charged 2",
    passive: "",
    refit: "",
    basicA: "Deal damage, remove 1 buff and apply DEFENSE DOWN III.",
chargedA: "Deal damage and apply EMP CHARGE II.",
cooldown: "4",
passiveM: "Damage increased for each enemy with DISABLE or STASIS. When enemy dies: Fill charge.",
    hp: 16950,
    attack: 4591,
    defense: 2166,
    hacking: 144,
    security: 33,
    critR: 6,
    critD: 30,
    speed: 71  
  },
   {
    name: "Zosimos",
    image: "images/chars/zosimos.png",
    affinity: "Antimatter",
    rarity: "Legendary",
    faction: "Everliving",
    role: "Debuffer",
    basic: ["inc. repair down 2", "inc. damage up 2"],
    charged: "block repair",
    passive: ["repair", "hacking up 2"],
    refit: "fill charge",
    basicA: "Deal damage, apply INC. REPAIR DOWN II and INC DAMAGE UP II",
chargedA: "Deal damage and apply INC. BLOCK REPAIR.",
cooldown: "8",
passiveM: "Enemy repaired: Repair self, gain HACKING UP II and fill charge.",
    hp: 18200,
    attack: 4201,
    defense: 2785,
    hacking: 147,
    security: 12,
    critR: 6,
    critD: 22,
    speed: 88 
  },
]

const resetButton = document.getElementById("resetButton");
resetButton.addEventListener("click", resetCards);

function resetCards() {
  document.getElementById('cardFilter').value = 'none';
  const cards = document.querySelectorAll(".card");
  cards.forEach((card) => {
    card.style.display = "block";
  });
}

hangar.sort((a, b) => {
  const rarityOrder = {
    legendary: 0,
    epic: 1,
    rare: 2
  };
  
  return rarityOrder[a.rarity.toLowerCase()] - rarityOrder[b.rarity.toLowerCase()];
});


const galleryContainer = document.querySelector(".gallery");
  
hangar.forEach((ship) => {
  const galleryContainer = document.querySelector(".gallery");
  galleryContainer.classList.add("gallery-container");
  const card = document.createElement("div");
  card.classList.add("card");

  if (ship.rarity.toLowerCase() === "legendary") {
    card.classList.add("legendary-card");
  } else if (ship.rarity.toLowerCase() === "epic") {
    card.classList.add("epic-card");
  } else if (ship.rarity.toLowerCase() === "rare") {
    card.classList.add("rare-card");
  }

  card.setAttribute("data-name", ship.name);

  const affinityIcon = document.createElement("div");
  affinityIcon.classList.add("affinity-icon");

  if (ship.affinity.toLowerCase() === "antimatter") {
    affinityIcon.classList.add("antimatter-affinity");
  } else if (ship.affinity.toLowerCase() === "chemical") {
    affinityIcon.classList.add("chemical-affinity");
  } else if (ship.affinity.toLowerCase() === "thermal") {
    affinityIcon.classList.add("thermal-affinity");
  } else if (ship.affinity.toLowerCase() === "electric") {
    affinityIcon.classList.add("electric-affinity");
  }

  const roleIcon = document.createElement("i");
  roleIcon.classList.add("role-icon");

  if (ship.role === "Supporter") {
    roleIcon.classList.add("bi", "bi-plus-circle");
  } else if (ship.role === "Defender") {
    roleIcon.classList.add("bi", "bi-shield-shaded");
  } else if (ship.role === "Attacker") {
    roleIcon.classList.add("bi", "bi-lightning-charge-fill");
  } else if (ship.role === "Debuffer") {
    roleIcon.classList.add("bi", "bi-bug-fill");
  } else {
    roleIcon.classList.add("bi", "bi-question-circle-fill");
  }

  card.appendChild(affinityIcon);
  card.appendChild(roleIcon);

  const image = document.createElement("img");
  image.src = ship.image;
  image.alt = ship.name;
  
  card.appendChild(image);
  
  galleryContainer.appendChild(card);
});



const cardFilter = document.getElementById("cardFilter");
cardFilter.addEventListener("change", filterCards);
 
function filterCards() {
  const selectedValue = cardFilter.value.toLowerCase();
  const cards = document.querySelectorAll(".card");

  cards.forEach((card) => {
    const cardName = card.getAttribute("data-name").toLowerCase();
    const cardBasicAbilities = hangar.find((ship) => ship.name.toLowerCase() === cardName).basic;
    const cardChargedAbilities = hangar.find((ship) => ship.name.toLowerCase() === cardName).charged;
    const cardPassiveAbility = hangar.find((ship) => ship.name.toLowerCase() === cardName).passive;
    const cardRefitAbility = hangar.find((ship) => ship.name.toLowerCase() === cardName).refit;

    if (
      (Array.isArray(cardBasicAbilities) && cardBasicAbilities.includes(selectedValue)) ||
      (Array.isArray(cardChargedAbilities) && cardChargedAbilities.includes(selectedValue)) ||
      (Array.isArray(cardPassiveAbility) && cardPassiveAbility.includes(selectedValue)) ||
      (Array.isArray(cardRefitAbility) && cardRefitAbility.includes(selectedValue)) ||
      (typeof cardBasicAbilities === "string" && cardBasicAbilities === selectedValue) ||
      (typeof cardChargedAbilities === "string" && cardChargedAbilities === selectedValue) ||
      (typeof cardPassiveAbility === "string" && cardPassiveAbility === selectedValue) ||
      (typeof cardRefitAbility === "string" && cardRefitAbility === selectedValue)
    ) {
      card.style.display = "block"; // 
    } else {
      card.style.display = "none"; 
    }
  });
}

const cards = document.querySelectorAll(".card");
const modal = document.getElementById("modal");
const clonedCardContainer = document.getElementById("clonedCard");
const closeButton = document.querySelector(".close");


cards.forEach((card) => {
  card.addEventListener("click", (event) => {
    const clickedCard = event.currentTarget;
    const clonedCard = clickedCard.cloneNode(true);
    const cardData = hangar.find((ship) => ship.name.toLowerCase() === clickedCard.getAttribute("data-name").toLowerCase());

    const clonedCardContainer = document.getElementById("clonedCard");
    const cardInfoContainer = document.getElementById("cardInfo");
    const skillsContainer = document.getElementById("skillsContainer");
    clonedCardContainer.innerHTML = "";
    
    clonedCardContainer.appendChild(clonedCard);

    clonedCard.style.boxShadow = "7px 7px 5px 0 rgba(0, 0, 0, 0.3)";
 
    cardInfoContainer.innerHTML = `
      <p style="text-align: left;">
        <strong><span style="color: orange;">ATTRIBUTES</span></strong><br>
        <strong style="float: left; width: 90px;">HP</strong><span style="float: right;">${cardData.hp}</span><br>
        <strong style="float: left; width: 90px;">Attack</strong><span style="float: right;">${cardData.attack}</span><br>
        <strong style="float: left; width: 90px;">Defense</strong><span style="float: right;">${cardData.defense}</span><br>
        <strong style="float: left; width: 90px;">Hacking</strong><span style="float: right;">${cardData.hacking}</span><br>
        <strong style="float: left; width: 90px;">Security</strong><span style="float: right;">${cardData.security}</span><br>
        <strong style="float: left; width: 90px;">Crit Rate</strong><span style="float: right;">${cardData.critR}%</span><br>
        <strong style="float: left; width: 90px;">Crit Dam.</strong><span style="float: right;">${cardData.critD}%</span><br>
        <strong style="float: left; width: 90px;">Speed</strong><span style="float: right;">${cardData.speed}</span>
      </p>
    `;

    const basicActiveContainer = document.createElement('div');
basicActiveContainer.id = 'basicActiveContainer'; 

const chargedActiveContainer = document.createElement('div');
chargedActiveContainer.id = 'chargedActiveContainer';

const passiveContainer = document.createElement('div');
passiveContainer.id = 'passiveContainer'; 


    basicActiveContainer.innerHTML = `
      <hr style="border-color:white;">
      <p><strong><span style="color: orange;">BASIC ACTIVE</span></strong></p>
      <p>${cardData.basicA}</p>
    `;

    chargedActiveContainer.innerHTML = `
      <p><strong><span style="color: orange;">CHARGED ACTIVE</span></strong><span style="color: #FFD700;"> Cooldown</span>: ${cardData.cooldown}</p>
      <p>${cardData.chargedA}</p>
    `;

    passiveContainer.innerHTML = `
      <p><strong><span style="color: orange;">PASSIVE</span></strong></p>
      <p>${cardData.passiveM}</p><br>
      <p styles="font-size: 8px;"><em>*Description based on maxed skills and refit 2+ character.</p>
    `;

    skillsContainer.innerHTML = ""; 
    
    skillsContainer.appendChild(basicActiveContainer);
    skillsContainer.appendChild(chargedActiveContainer);
    skillsContainer.appendChild(passiveContainer);

    modal.style.display = "block"; 
    
    closeButton.addEventListener("click", () => {
      modal.style.display = "none";
    });
  });
});
